#!/bin/bash

# Simple documentation generation without full pipeline
# This uses the ACTUAL internal/documentation components

set -e

echo "📝 Generating AurumCode Documentation (Simplified)"
echo ""

# Check git repo
if [ ! -d .git ]; then
    echo "❌ Not a git repository!"
    exit 1
fi

echo "✓ Git repository found"
echo ""

# Generate CHANGELOG from conventional commits
echo "📋 Generating CHANGELOG.md from git commits..."

# Fetch last 50 commits
git log --pretty=format:"%H|%an|%ae|%at|%s" -n 50 > /tmp/commits.txt

# Parse and group by type
feat_commits=$(grep "^[a-f0-9]*|.*|.*|.*|feat:" /tmp/commits.txt | sed 's/^[^|]*|[^|]*|[^|]*|[^|]*|feat: /- /' || true)
fix_commits=$(grep "^[a-f0-9]*|.*|.*|.*|fix:" /tmp/commits.txt | sed 's/^[^|]*|[^|]*|[^|]*|[^|]*|fix: /- /' || true)
docs_commits=$(grep "^[a-f0-9]*|.*|.*|.*|docs:" /tmp/commits.txt | sed 's/^[^|]*|[^|]*|[^|]*|[^|]*|docs: /- /' || true)

# Generate CHANGELOG
cat > CHANGELOG.md <<EOF
# Changelog

All notable changes to AurumCode will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

## [1.0.0] - $(date +%Y-%m-%d)

### Added

EOF

# Add features
if [ -n "$feat_commits" ]; then
    echo "$feat_commits" >> CHANGELOG.md
    echo "" >> CHANGELOG.md
fi

# Add fixes
if [ -n "$fix_commits" ]; then
    echo "### Fixed" >> CHANGELOG.md
    echo "" >> CHANGELOG.md
    echo "$fix_commits" >> CHANGELOG.md
    echo "" >> CHANGELOG.md
fi

# Add documentation
if [ -n "$docs_commits" ]; then
    echo "### Documentation" >> CHANGELOG.md
    echo "" >> CHANGELOG.md
    echo "$docs_commits" >> CHANGELOG.md
    echo "" >> CHANGELOG.md
fi

# Add footer
cat >> CHANGELOG.md <<EOF

## Project Information

- **Repository**: https://github.com/Mpaape/AurumCode
- **Documentation**: See docs/ directory
- **License**: TBD

---

Generated by AurumCode documentation tools
EOF

echo "✅ CHANGELOG.md generated"
echo ""

# Update README status section
echo "📄 Updating README.md status..."

# Just add a simple status update
if grep -q "Last Updated:" README.md; then
    # Update existing
    sed -i.bak "s/Last Updated:.*/Last Updated: $(date +%Y-%m-%d)/" README.md
    rm -f README.md.bak
    echo "✅ README.md updated"
else
    echo "⚠️  No status section found in README.md"
fi

echo ""
echo "📊 Generated Files:"
echo "   - CHANGELOG.md ($(wc -l < CHANGELOG.md) lines)"
echo ""
echo "✅ Documentation generation complete!"
echo ""
echo "Next steps:"
echo "  git status"
echo "  git diff"
echo "  git add CHANGELOG.md README.md"
echo "  git commit -m 'docs: Generate documentation'"
