#!/usr/bin/env bash
# E2E check for AUR-447: build (or reuse) the real aurumcode binary and run
# `aurumcode docs --source <projeto Rust ou C#>` as a user would, against a
# real Rust project (tests/fixtures/docs/rustproject) and a real, ephemeral
# C# project, with no network and no environment variable the user has to
# discover first. Also proves Go keeps working (tests/fixtures/docs/
# goproject, AUR-426's own fixture) and that `aurumcode review` against the
# tests/fixtures/repos/git-demo fixture keeps its exact published contract.
# See docs/specs/AUR-447.md.
set -euo pipefail
export LC_ALL=C

readonly card=AUR-447
selector="${1:-E2EAUR447}"
[[ "$selector" == "E2EAUR447" ]] || { printf '%s/AC-001/unknown-selector\n' "$card" >&2; exit 64; }

fail() { printf '%s/AC-001/%s\n' "$card" "$1" >&2; exit 1; }
infra() { printf '%s/AC-001/infrastructure/%s\n' "$card" "$1" >&2; exit 79; }

script_dir="${0%/*}"; [[ "$script_dir" != "$0" ]] || script_dir='.'
repo_root="$(CDPATH='' cd -- "$script_dir/../.." && pwd -P)" || infra repo_root

command -v go >/dev/null 2>&1 || infra missing_go

rust_dir="$repo_root/tests/fixtures/docs/rustproject"
test -d "$rust_dir" || infra missing_rustproject_fixture
go_dir="$repo_root/tests/fixtures/docs/goproject"
test -d "$go_dir" || infra missing_goproject_fixture
repo_dir="$repo_root/tests/fixtures/repos/git-demo/repo.git"
test -d "$repo_dir" || infra missing_git_demo_fixture

run_dir="$(mktemp -d "${TMPDIR:-/tmp}/aurum-e2e-a447.XXXXXX")" || infra mktemp
# See tests/acceptance/AUR-430.sh's cleanup_root: never let a removal error
# override an already-decided result.
trap 'chmod -R u+w -- "$run_dir" >/dev/null 2>&1 || true; rm -rf -- "$run_dir" >/dev/null 2>&1 || true' EXIT INT TERM HUP

mkdir -p "$run_dir/gocache" "$run_dir/gotmp"
# Reuse an already-warm build cache and an already-built binary when a
# caller provides them (tests/acceptance/AUR-447.sh's e2e_case does).
# Standalone invocation falls back to building its own, isolated copy.
: "${GOCACHE:=$run_dir/gocache}"
: "${GOTMPDIR:=$run_dir/gotmp}"
export GOCACHE GOTMPDIR

if [[ -n "${AURUMCODE_BIN:-}" ]]; then
  bin="$AURUMCODE_BIN"
  test -x "$bin" || infra missing_prebuilt_binary
else
  bin="$run_dir/aurumcode"
  build_log="$run_dir/build.log"
  if ! (cd "$repo_root" && GOFLAGS=-mod=mod go build -o "$bin" ./cmd/aurumcode) >"$build_log" 2>&1; then
    cat "$build_log" >&2
    fail build_failed
  fi
fi

# run_docs runs the binary as a user would; raw exit code lands in rc,
# stdout/stderr in $run_dir/out.{stdout,stderr}.
run_docs() {
  set +e
  (cd "$repo_root" && "$bin" docs "$@") \
    >"$run_dir/out.stdout" 2>"$run_dir/out.stderr"
  rc=$?
  set -e
}

# The declared command, against the card's own Rust fixture: real
# documentation, generated by driving the same native, tool-free extractor
# (internal/documentation/extractors/rust) cmd/regenerate-docs already
# registers by default.
rust_out="$run_dir/rust-site"
run_docs --source "$rust_dir" --output "$rust_out"
[[ "$rc" -eq 0 ]] || fail "rust_generation_failed:exit:$rc"
rust_page="$rust_out/rust/src__lib.md"
test -s "$rust_page" || fail missing_generated_rust_page
grep -Fq 'pub struct Entry' "$rust_page" || fail generated_rust_page_missing_real_symbol
grep -Fq 'pub fn new_entry' "$rust_page" || fail generated_rust_page_missing_real_symbol
grep -Fq 'pub fn record_internal' "$rust_page" && fail rust_page_false_claim

# The declared command, against a real, ephemeral C# project (this card's
# `paths` grants no checked-in C# fixture; see docs/specs/AUR-447.md).
cs_dir="$run_dir/csharpproject"
mkdir -p "$cs_dir"
cat >"$cs_dir/Greeter.cs" <<'CSEOF'
namespace Fixture
{
    /// <summary>
    /// A greeter that says hello in a configurable language.
    /// </summary>
    public class Greeter
    {
        /// <summary>
        /// Creates a greeter for the given language tag.
        /// </summary>
        /// <param name="lang">A BCP-47-ish language tag, e.g. "en" or "pt".</param>
        public Greeter(string lang)
        {
            Lang = lang;
        }

        /// <summary>
        /// The greeter's configured language tag.
        /// </summary>
        public string Lang { get; }

        /// <summary>
        /// Renders a greeting for the given name.
        /// </summary>
        /// <returns>A human-readable greeting sentence.</returns>
        public string Greet(string name)
        {
            return Lang == "pt" ? "Ola, " + name + "!" : "Hello, " + name + "!";
        }
    }
}
CSEOF
cs_out="$run_dir/cs-site"
run_docs --source "$cs_dir" --output "$cs_out"
[[ "$rc" -eq 0 ]] || fail "csharp_generation_failed:exit:$rc"
cs_page="$cs_out/csharp/Greeter.md"
test -s "$cs_page" || fail missing_generated_csharp_page
grep -Fq 'public class Greeter' "$cs_page" || fail generated_csharp_page_missing_real_symbol
grep -Fq 'public string Greet(string name)' "$cs_page" || fail generated_csharp_page_missing_real_symbol

# Go keeps working: AUR-426's own fixture and expected page, unregressed by
# this card's fix.
go_out="$run_dir/go-site"
run_docs --source "$go_dir" --output "$go_out"
[[ "$rc" -eq 0 ]] || fail "go_generation_failed:exit:$rc"
go_page="$go_out/go/root.md"
test -f "$go_page" || fail missing_generated_go_page
grep -Fq 'Greeting' "$go_page" || fail generated_go_page_missing_real_symbol
grep -Fq 'func Add' "$go_page" || fail generated_go_page_missing_real_symbol

# Determinism: repeating the Rust run over the same input produces the same
# output (AC-001's "repetir a execucao sobre a mesma entrada produz a mesma
# saida").
first_stdout="$(cat "$run_dir/out.stdout")"
run_docs --source "$go_dir" --output "$go_out"
[[ "$rc" -eq 0 ]] || fail "second_run_failed:exit:$rc"
[[ "$(cat "$run_dir/out.stdout")" == "$first_stdout" ]] || fail non_deterministic_output

# Non-regression: aurumcode review's published contract (AUR-430/431) is
# byte-for-byte unchanged by this card.
fixture="$run_dir/response-clean.json"
cat >"$fixture" <<'EOF'
{"issues":[],"summary":"Nothing to report."}
EOF
set +e
(cd "$repo_dir" && AURUMCODE_LLM_FIXTURE="$fixture" "$bin" review --base HEAD~1) \
  >"$run_dir/review.stdout" 2>"$run_dir/review.stderr"
rc=$?
set -e
[[ "$rc" -eq 0 ]] || fail "review_regression:exit:$rc"
[[ "$(cat "$run_dir/review.stdout")" == "No issues found." ]] || fail review_contract_changed

printf '%s/AC-001/E2EAUR447/ok\n' "$card"
