#!/usr/bin/env bash
# E2E check for AUR-426: build (or reuse) the real aurumcode binary and run
# `aurumcode docs --help` and `aurumcode docs --source ... --output ...` as a
# user would, against the tests/fixtures/docs/goproject fixture, with no
# network and no environment variable the user has to discover first.
# Also proves the card's non-regression promise: `aurumcode review` against
# the tests/fixtures/repos/git-demo fixture keeps its exact published
# contract. See docs/specs/AUR-426.md.
set -euo pipefail
export LC_ALL=C

readonly card=AUR-426
selector="${1:-E2EAUR426}"
[[ "$selector" == "E2EAUR426" ]] || { printf '%s/AC-001/unknown-selector\n' "$card" >&2; exit 64; }

fail() { printf '%s/AC-001/%s\n' "$card" "$1" >&2; exit 1; }
infra() { printf '%s/AC-001/infrastructure/%s\n' "$card" "$1" >&2; exit 79; }

script_dir="${0%/*}"; [[ "$script_dir" != "$0" ]] || script_dir='.'
repo_root="$(CDPATH='' cd -- "$script_dir/../.." && pwd -P)" || infra repo_root

command -v go >/dev/null 2>&1 || infra missing_go

goproject_dir="$repo_root/tests/fixtures/docs/goproject"
test -d "$goproject_dir" || infra missing_goproject_fixture
repo_dir="$repo_root/tests/fixtures/repos/git-demo/repo.git"
test -d "$repo_dir" || infra missing_git_demo_fixture

run_dir="$(mktemp -d "${TMPDIR:-/tmp}/aurum-e2e-a426.XXXXXX")" || infra mktemp
# See tests/acceptance/AUR-430.sh's cleanup_root: never let a removal error
# override an already-decided result.
trap 'chmod -R u+w -- "$run_dir" >/dev/null 2>&1 || true; rm -rf -- "$run_dir" >/dev/null 2>&1 || true' EXIT INT TERM HUP

mkdir -p "$run_dir/gocache" "$run_dir/gotmp"
# Reuse an already-warm build cache and an already-built binary when a
# caller provides them (tests/acceptance/AUR-426.sh's e2e_case does).
# Standalone invocation falls back to building its own, isolated copy.
: "${GOCACHE:=$run_dir/gocache}"
: "${GOTMPDIR:=$run_dir/gotmp}"
export GOCACHE GOTMPDIR

if [[ -n "${AURUMCODE_BIN:-}" ]]; then
  bin="$AURUMCODE_BIN"
  test -x "$bin" || infra missing_prebuilt_binary
else
  bin="$run_dir/aurumcode"
  build_log="$run_dir/build.log"
  if ! (cd "$repo_root" && GOFLAGS=-mod=mod go build -o "$bin" ./cmd/aurumcode) >"$build_log" 2>&1; then
    cat "$build_log" >&2
    fail build_failed
  fi
fi

# run_docs runs the binary as a user would; raw exit code lands in rc,
# stdout/stderr in $run_dir/out.{stdout,stderr}.
run_docs() {
  set +e
  (cd "$repo_root" && "$bin" docs "$@") \
    >"$run_dir/out.stdout" 2>"$run_dir/out.stderr"
  rc=$?
  set -e
}

# --help documents usage on stdout, exit 0. No environment variable was
# consulted -- the whole point is discoverability without a spec or the
# source in hand.
run_docs --help
[[ "$rc" -eq 0 ]] || fail "help_failed:exit:$rc"
[[ -s "$run_dir/out.stderr" ]] && fail help_wrote_stderr
grep -Fq 'usage: aurumcode docs' "$run_dir/out.stdout" || fail help_missing_usage_line
for flag in -source -output -languages; do
  grep -Fq -- "$flag" "$run_dir/out.stdout" || fail "help_missing_flag:$flag"
done

# The declared command, against the declared fixture: real documentation,
# generated by driving internal/pipeline through discoverable flags, never
# an environment variable the user had to already know.
out_dir="$run_dir/site"
run_docs --source "$goproject_dir" --output "$out_dir"
[[ "$rc" -eq 0 ]] || fail "generation_failed:exit:$rc"
page="$out_dir/go/root.md"
test -f "$page" || fail missing_generated_page
grep -Fq 'Greeting' "$page" || fail generated_page_missing_real_symbol
grep -Fq 'func Add' "$page" || fail generated_page_missing_real_symbol
first_stdout="$(cat "$run_dir/out.stdout")"

# Determinism: repeating the run over the same input produces the same
# output (AC-001's "repetir a execucao sobre a mesma entrada produz a mesma
# saida").
run_docs --source "$goproject_dir" --output "$out_dir"
[[ "$rc" -eq 0 ]] || fail "second_run_failed:exit:$rc"
[[ "$(cat "$run_dir/out.stdout")" == "$first_stdout" ]] || fail non_deterministic_output

# A source that does not exist fails clearly, exit 1 -- never a silent
# empty success.
run_docs --source "$run_dir/does-not-exist" --output "$run_dir/site2"
[[ "$rc" -eq 1 ]] || fail "missing_source_wrong_exit:$rc"
grep -Fq 'source directory' "$run_dir/out.stderr" || fail missing_source_error_unclear

# A --languages filter that matches nothing in the fixture documents zero
# pages, and that is a failure, exit 1 -- never a green run with nothing on
# disk.
run_docs --source "$goproject_dir" --output "$run_dir/site3" --languages nonexistent-language
[[ "$rc" -eq 1 ]] || fail "empty_run_wrong_exit:$rc"
grep -Fq 'no documentation page was generated' "$run_dir/out.stderr" || fail empty_run_message_missing

# Non-regression: aurumcode review's published contract (AUR-430/431) is
# byte-for-byte unchanged by this card.
fixture="$run_dir/response-clean.json"
cat >"$fixture" <<'EOF'
{"issues":[],"summary":"Nothing to report."}
EOF
set +e
(cd "$repo_dir" && AURUMCODE_LLM_FIXTURE="$fixture" "$bin" review --base HEAD~1) \
  >"$run_dir/review.stdout" 2>"$run_dir/review.stderr"
rc=$?
set -e
[[ "$rc" -eq 0 ]] || fail "review_regression:exit:$rc"
[[ "$(cat "$run_dir/review.stdout")" == "No issues found." ]] || fail review_contract_changed

printf '%s/AC-001/E2EAUR426/ok\n' "$card"
