#!/usr/bin/env bash
# AUR-361 / AC-001 - bootstrap action lock.
#
# DESIGN NOTE (round 3 redesign).
#
# Round 1 ASSERTED: a human wrote `entry_NNN_*` records into
# `.board/bootstrap/locks/actions.yml` and the gate decided pass/fail from
# whole-file digests only, so a stale entry set never blocked anything.
#
# Round 2 DERIVED the lock: the whole file is a pure function of the scanned
# bytes, produced by `--generate` in this same file, and the gate regenerates
# it into a temporary file and compares byte for byte. That killed "a field
# nobody recomputes" and it is KEPT here unchanged.
#
# Round 2 still lost to the surviving class: THE CHECK THAT NEVER RUNS. Two
# live bypasses were demonstrated inside the sealed container with exit 0:
#
#   B1  `owner_is_trusted` was called only when `entry_kind == remote`, so a
#       `uses: docker://evil-registry.example.com/malware@sha256:<64hex>` was
#       recorded with the literal owner string "docker" and never compared to
#       any allowlist.
#   B2  a `uses: ./path` was hashed for INTEGRITY but never OPENED, so a
#       composite action's own `uses:` lines were never derived, never
#       classified, and never policed.
#
# Both are the same defect: the program classified by BRANCH, one branch per
# input shape, and some branch skipped the check. Round 3 removes the branches
# instead of adding one more:
#
#   1. TRANSITIVE CLOSURE. `derive_lock` no longer enumerates a fixed file
#      list. It seeds a worklist with `.github/workflows/**` plus the root
#      `action.yml`, and every local `uses:` target discovered while scanning
#      is ENQUEUED into the same worklist, to a fixed point, with cycle
#      detection (an already-enqueued path is never re-enqueued; an already
#      visited path being dequeued twice is a hard reject) and with the
#      counts asserted: visited == enqueued == queue length. A second,
#      independent assertion in the entry phase proves every local entry's
#      resolved target is a member of the closed file set, so a scan that
#      missed an edge cannot pass silently.
#
#   2. ONE POLICY, ZERO BRANCHES. There is a single origin allowlist keyed by
#      (source, owner) and it is applied to EVERY derived entry with no
#      conditional whatsoever. `entry_kind` may change HOW the owner is
#      extracted; it can never change WHETHER the owner is checked. The loop
#      counts its own applications and refuses unless the count equals the
#      entry count, so "the check silently did not run" is itself a failure
#      mode with a typed code. An unknown source value fails closed.
#
# Emptiness is never success: zero input files, zero derived `uses:` sites, a
# missing live floor, or an empty allowlist are all explicit refusals.
#
# Reference truth is the workflow files. The lock is the derivative. The
# fixture suite under tests/bootstrap/locks/AUR-361 is checked against
# hand-written expectations in cases.tsv, which are NOT generated by this
# script, so no comparison in this file is a copy of the thing it verifies.
#
# One more finding of round 3, from mutation-testing THIS file: asserting only
# the typed code was not enough evidence. Several controls share the code
# `invalid_lock_or_manifest`, so deleting the `no-input-files` control or the
# `zero-uses-sites-derived` control left the suite green - a redundant control
# refused with the same code and no row could tell. That is the same class
# again, one level up: the check stopped running and nothing observed it. Each
# refusing fixture row therefore also names the exact control that must fire
# (`reason` column), asserted as a colon-delimited field of the detail, with
# the usual count assertion. Both mutants now die.

set -euo pipefail

export LC_ALL=C
umask 077

readonly card='AUR-361'
readonly scenario='AC-001'

# ---------------------------------------------------------------------------
# Hard-coded policy. None of this is read from the lock, from a workflow, or
# from any repository data: a value the attacker can edit inside the material
# under test cannot be allowed to widen the policy that judges that material.
# ---------------------------------------------------------------------------

# Bounds from the card: 256 entries, 4 MiB, 256 input files.
readonly max_entries=256
readonly max_input_files=256
readonly max_input_bytes=4194304

# THE single origin allowlist. One table, `source<TAB>owner`, consulted for
# every derived entry regardless of kind. `repository/in-tree` is present so
# that an in-repo composite action is ALLOWED by the same rule that judges a
# remote action - not by skipping the rule. Its contents are then themselves
# closed over by the worklist, so "in-tree" is a statement about provenance,
# not an exemption from analysis.
readonly trusted_origins='github-remote	actions
github-remote	ruby
github-remote	Mpaape
container-registry	docker.io/library
repository	in-tree'

# Pre-existing floating-tag debt. `.github/workflows/ci.yml` and
# `.github/workflows/documentation.yml` shipped before this card and reference
# trusted actions by mutable tag. The card's Non-goals forbid this card from
# rewriting a mutable `uses:`, and `.github/workflows` is a read_path here, so
# the debt cannot be repaid inside AUR-361. It is therefore frozen: each
# identity@ref below is tolerated up to the recorded count and NOT beyond.
# A new floating reference, a floating reference at a higher count, or a
# floating reference on any other identity fails. Repaying debt (count going
# down) is always allowed. This register lives here, in the acceptance
# program, so growing it is a visible diff in the card's own reviewed paths;
# it is never sourced from the lock.
readonly frozen_floating_debt='actions/checkout@v4	3
actions/setup-go@v5	3
actions/upload-artifact@v4	2
actions/upload-pages-artifact@v3	1
actions/github-script@v7	1
actions/deploy-pages@v4	1
ruby/setup-ruby@v1	1'

# Structural floor for the live repository. Emptiness is never success: a tree
# with no workflows, or a workflows tree with no `uses:` site, is a broken
# board, not a clean one.
readonly live_required_file='action.yml'
readonly live_required_dir='.github/workflows'

# shellcheck disable=SC1007  # `CDPATH= cd` is a deliberate prefix assignment.
repo_root="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd -P)"
readonly repo_root
readonly lock_path='.board/bootstrap/locks/actions.yml'
readonly fixture_dir='tests/bootstrap/locks/AUR-361'
readonly spec_path='docs/specs/AUR-361.md'
readonly self_path='tests/acceptance/AUR-361.sh'

# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------

L361_CODE=''
L361_DETAIL=''

reject() {
  L361_CODE="$1"
  L361_DETAIL="${2-}"
  return 1
}

fail() {
  local code="$1"
  local detail="${2-}"
  printf '%s/%s/%s\n' "$card" "$scenario" "$code" >&2
  [[ -z "$detail" ]] || printf '%s/%s/detail %s\n' "$card" "$scenario" "$detail" >&2
  exit 1
}

# ---------------------------------------------------------------------------
# Primitives
# ---------------------------------------------------------------------------

digest_of() {
  local out
  out="$(sha256sum <"$1")" || return 1
  printf 'sha256:%s' "${out%% *}"
}

digest_of_string() {
  local out
  out="$(printf '%s' "$1" | sha256sum)" || return 1
  printf 'sha256:%s' "${out%% *}"
}

byte_size_of() {
  local out
  out="$(wc -c <"$1")" || return 1
  printf '%s' "${out//[[:space:]]/}"
}

ltrim() {
  local v="$1"
  printf '%s' "${v#"${v%%[![:space:]]*}"}"
}

array_contains() {
  local needle="$1"
  shift
  local element
  for element in "$@"; do
    [[ "$element" != "$needle" ]] || return 0
  done
  return 1
}

# NUL detection. Law 15: BusyBox awk and grep mis-handle a NUL and bash `read`
# drops it silently, so neither may be used to decide this. `tr -cd` plus
# `wc -c` counts the bytes directly.
count_nul_bytes() {
  local out
  out="$(tr -cd '\000' <"$1" | wc -c)" || return 1
  printf '%s' "${out//[[:space:]]/}"
}

count_cr_bytes() {
  local out
  out="$(tr -cd '\015' <"$1" | wc -c)" || return 1
  printf '%s' "${out//[[:space:]]/}"
}

# ---------------------------------------------------------------------------
# Line scanner
#
# Derivation of `uses:` sites is line-based on purpose. A YAML object model
# (an earlier round used one in Go) silently loses whole documents after the
# first `---` and attributes merge-key reuse to the wrong site; a line scan
# loses neither. Every construct the scanner cannot reason about is REJECTED,
# not skipped, so "no blind spot" is enforced rather than asserted.
#
# A line is inspected in three stages:
#   1. full-line comment  -> inert, by YAML's own rule
#   2. unsupported construct (explicit key `?`, merge key `<<:`, anchor,
#      alias) -> hard reject
#   3. split into flow segments at `{`, `[`, `,`; a segment is an active
#      `uses:` key iff, after stripping leading whitespace and the structural
#      characters `-`, `"`, `'`, it begins with `uses` + optional quote +
#      optional whitespace + `:`.
#
# Stage 3 cannot produce a false negative from splitting: splitting only makes
# more segments and a real `uses:` key always begins its own segment. It can
# produce a false positive (a `uses:` inside a quoted scalar that happens to
# follow a comma); that direction is fail-closed and is proven by fixture.
# ---------------------------------------------------------------------------

SCAN_ACTIVE_VALUES=()

scan_line_unsupported() {
  local line="$1"
  local body
  body="$(ltrim "$line")"
  [[ "${body:0:1}" != '#' ]] || return 0
  local naked="$body"
  while [[ "$naked" == '- '* || "$naked" == $'-\t'* || "$naked" == '-' ]]; do
    naked="$(ltrim "${naked:1}")"
  done
  if [[ "$body" == '?' || "$body" == '? '* || "$body" == $'?\t'* ||
        "$naked" == '?' || "$naked" == '? '* || "$naked" == $'?\t'* ]]; then
    reject invalid_lock_or_manifest 'explicit-key-indicator'
    return 1
  fi
  if [[ "$line" == *'<<:'* ]]; then
    reject invalid_lock_or_manifest 'merge-key'
    return 1
  fi
  if [[ "$naked" =~ ^[\&\*][A-Za-z0-9_][A-Za-z0-9_.-]*[[:space:]]*$ ]]; then
    reject invalid_lock_or_manifest 'yaml-anchor-or-alias'
    return 1
  fi
  if [[ "$naked" =~ ^[A-Za-z0-9_.-]+:[[:space:]]+[\&\*][A-Za-z0-9_][A-Za-z0-9_.-]*[[:space:]]*$ ]]; then
    reject invalid_lock_or_manifest 'yaml-anchor-or-alias'
    return 1
  fi
  return 0
}

# Does the line carry the textual token `uses:` at all (quote tolerated
# between the word and the colon)? Used only to decide whether an unmatched
# line is worth recording as an inert witness.
line_carries_uses_token() {
  local lower="${1,,}"
  local rest
  while [[ "$lower" == *uses* ]]; do
    rest="${lower#*uses}"
    [[ "${rest:0:1}" != '"' && "${rest:0:1}" != "'" ]] || rest="${rest:1}"
    rest="$(ltrim "$rest")"
    [[ "${rest:0:1}" != ':' ]] || return 0
    lower="${lower#*uses}"
  done
  return 1
}

segment_uses_value() {
  local seg="$1"
  local rest lower value
  seg="$(ltrim "$seg")"
  while [[ "${seg:0:1}" == '-' || "${seg:0:1}" == '"' || "${seg:0:1}" == "'" ]]; do
    seg="$(ltrim "${seg:1}")"
  done
  [[ "${seg:0:1}" != '#' ]] || return 1
  lower="${seg,,}"
  [[ "$lower" == uses* ]] || return 1
  rest="${seg:4}"
  [[ "${rest:0:1}" != '"' && "${rest:0:1}" != "'" ]] || rest="${rest:1}"
  rest="$(ltrim "$rest")"
  [[ "${rest:0:1}" == ':' ]] || return 1
  value="$(ltrim "${rest:1}")"
  if [[ "${value:0:1}" == '"' ]]; then
    value="${value:1}"
    value="${value%%\"*}"
  elif [[ "${value:0:1}" == "'" ]]; then
    value="${value:1}"
    value="${value%%\'*}"
  else
    value="${value%%[[:space:]]*}"
    value="${value%%\}*}"
    value="${value%%\]*}"
  fi
  printf '%s' "$value"
}

# Fills SCAN_ACTIVE_VALUES with every active `uses:` value on the line.
# Returns 1 (with L361_CODE set) on an unsupported construct.
scan_line() {
  local line="$1"
  local body blob seg value
  SCAN_ACTIVE_VALUES=()
  scan_line_unsupported "$line" || return 1
  body="$(ltrim "$line")"
  [[ "${body:0:1}" != '#' ]] || return 0
  blob="${line//\{/$'\n'}"
  blob="${blob//\[/$'\n'}"
  blob="${blob//,/$'\n'}"
  while IFS= read -r seg; do
    value="$(segment_uses_value "$seg")" || continue
    SCAN_ACTIVE_VALUES+=("$value")
  done <<<"$blob"
  return 0
}

# ---------------------------------------------------------------------------
# File scanner
#
# ONE scanner, used by BOTH the closure phase and the entry phase, so a file
# reached through a local `uses:` is read by exactly the same code that reads
# a workflow. There is no "second, lighter" pass for nested inputs.
#
# The `continue` statements inside the loop are guarded by the count assertion
# at the bottom: every line that carries the `uses` token is accounted for as
# either an active-value line, an inert witness, or a non-`uses:` false hit,
# and the three counts must not exceed the carrier count.
# ---------------------------------------------------------------------------

FILE_VALUES=()
FILE_LINES=()
FILE_LINE_SHA=()
FILE_INERT_LINES=()
FILE_INERT_SHA=()

scan_file() {
  local abs="$1"
  local rel="$2"
  local rawline lineno=0 value
  local carrier_lines=0 active_lines=0 linesha
  FILE_VALUES=(); FILE_LINES=(); FILE_LINE_SHA=()
  FILE_INERT_LINES=(); FILE_INERT_SHA=()
  while IFS= read -r rawline || [[ -n "$rawline" ]]; do
    lineno=$((lineno + 1))
    case "$rawline" in
      *[uU][sS][eE][sS]*) ;;
      *) continue ;;
    esac
    carrier_lines=$((carrier_lines + 1))
    scan_line "$rawline" || { L361_DETAIL="$rel:$lineno:$L361_DETAIL"; return 1; }
    if (( ${#SCAN_ACTIVE_VALUES[@]} == 0 )); then
      if line_carries_uses_token "$rawline"; then
        FILE_INERT_LINES+=("$lineno")
        FILE_INERT_SHA+=("$(digest_of_string "$rawline")")
      fi
      continue
    fi
    active_lines=$((active_lines + 1))
    linesha="$(digest_of_string "$rawline")"
    for value in "${SCAN_ACTIVE_VALUES[@]}"; do
      FILE_VALUES+=("$value")
      FILE_LINES+=("$lineno")
      FILE_LINE_SHA+=("$linesha")
    done
  done <"$abs"
  # Count assertions beside the `continue`s above.
  (( ${#FILE_VALUES[@]} == ${#FILE_LINES[@]} && ${#FILE_VALUES[@]} == ${#FILE_LINE_SHA[@]} )) ||
    { reject invalid_lock_or_manifest "scan-value-drift:$rel:${#FILE_VALUES[@]}/${#FILE_LINES[@]}/${#FILE_LINE_SHA[@]}"; return 1; }
  (( ${#FILE_INERT_LINES[@]} == ${#FILE_INERT_SHA[@]} )) ||
    { reject invalid_lock_or_manifest "scan-inert-drift:$rel"; return 1; }
  (( active_lines + ${#FILE_INERT_LINES[@]} <= carrier_lines )) ||
    { reject invalid_lock_or_manifest "scan-carrier-drift:$rel:$active_lines+${#FILE_INERT_LINES[@]}>$carrier_lines"; return 1; }
  (( active_lines <= ${#FILE_VALUES[@]} )) ||
    { reject invalid_lock_or_manifest "scan-active-drift:$rel:$active_lines>${#FILE_VALUES[@]}"; return 1; }
  return 0
}

# ---------------------------------------------------------------------------
# Local-action resolution
#
# Shared by the closure phase and by classification, so the path a nested
# scan follows is byte-identical to the path whose digest is recorded. Every
# component is checked for a symlink, not just the final one: a symlinked
# intermediate directory is a redirect of the material under test.
# ---------------------------------------------------------------------------

LOCAL_TARGET=''
LOCAL_TARGET_REL=''

value_is_local() {
  [[ "$1" == './'* || "$1" == '.' ]]
}

resolve_local_target() {
  local value="$1"
  local root="$2"
  local rel remainder part acc target slashes expected=0 walked=0
  LOCAL_TARGET=''
  LOCAL_TARGET_REL=''

  [[ "$value" != *'@'* ]] ||
    { reject invalid_lock_or_manifest 'local-action-carries-ref'; return 1; }
  [[ "/$value/" != */../* ]] ||
    { reject source_integrity_error 'local-action-path-escape'; return 1; }
  value_is_local "$value" ||
    { reject invalid_lock_or_manifest 'local-action-not-relative'; return 1; }

  rel="${value#./}"
  [[ "$value" != '.' ]] || rel=''
  rel="${rel%/}"
  [[ "$rel" != *'//'* ]] ||
    { reject invalid_lock_or_manifest 'local-action-path-malformed'; return 1; }

  # Independent segment count, computed by a different method than the walk.
  if [[ -n "$rel" ]]; then
    slashes="${rel//[^\/]/}"
    expected=$(( ${#slashes} + 1 ))
  fi

  acc="$root"
  remainder="$rel"
  while [[ -n "$remainder" ]]; do
    part="${remainder%%/*}"
    if [[ "$part" == "$remainder" ]]; then
      remainder=''
    else
      remainder="${remainder#*/}"
    fi
    [[ -n "$part" && "$part" != '.' ]] ||
      { reject invalid_lock_or_manifest 'local-action-path-malformed'; return 1; }
    acc="$acc/$part"
    walked=$((walked + 1))
    [[ ! -L "$acc" ]] ||
      { reject source_integrity_error 'local-action-path-symlink'; return 1; }
    [[ -e "$acc" ]] ||
      { reject source_integrity_error 'local-action-missing'; return 1; }
  done
  (( walked == expected )) ||
    { reject invalid_lock_or_manifest "local-action-segment-drift:$walked/$expected"; return 1; }

  target="$acc"
  if [[ -d "$target" ]]; then
    if [[ -f "$target/action.yml" && ! -L "$target/action.yml" ]]; then
      target="$target/action.yml"
    elif [[ -f "$target/action.yaml" && ! -L "$target/action.yaml" ]]; then
      target="$target/action.yaml"
    else
      reject source_integrity_error 'local-action-without-manifest'
      return 1
    fi
  elif [[ ! -f "$target" ]]; then
    reject source_integrity_error 'local-action-not-a-regular-file'
    return 1
  fi

  LOCAL_TARGET="$target"
  LOCAL_TARGET_REL="${target#"$root/"}"
  [[ "$LOCAL_TARGET_REL" != "$target" ]] ||
    { reject source_integrity_error 'local-action-outside-root'; return 1; }
  return 0
}

# ---------------------------------------------------------------------------
# Container image normalisation
#
# A `docker://` reference has a real registry and a real namespace. Round 2
# recorded the literal string "docker" as the owner, which made the origin
# allowlist meaningless for that shape. Normalising to
# `<registry>/<namespace...>/<image>` gives the SAME table a real owner to
# judge, so no separate rule and no separate branch is needed.
# ---------------------------------------------------------------------------

DOCKER_IDENTITY=''
DOCKER_OWNER=''

docker_normalize() {
  local image="$1"
  local registry path first
  DOCKER_IDENTITY=''
  DOCKER_OWNER=''
  [[ "$image" =~ ^[A-Za-z0-9][A-Za-z0-9._:/-]*$ ]] ||
    { reject invalid_lock_or_manifest 'unparseable-docker-image'; return 1; }
  [[ "$image" != *'//'* && "$image" != */ ]] ||
    { reject invalid_lock_or_manifest 'unparseable-docker-image'; return 1; }
  first="${image%%/*}"
  if [[ "$image" == */* && ( "$first" == *.* || "$first" == *:* || "$first" == 'localhost' ) ]]; then
    registry="$first"
    path="${image#*/}"
  else
    registry='docker.io'
    path="$image"
    [[ "$path" == */* ]] || path="library/$path"
  fi
  [[ -n "$registry" && -n "$path" ]] ||
    { reject invalid_lock_or_manifest 'unparseable-docker-image'; return 1; }
  DOCKER_IDENTITY="$registry/$path"
  if [[ "$path" == */* ]]; then
    DOCKER_OWNER="$registry/${path%/*}"
  else
    DOCKER_OWNER="$registry"
  fi
  return 0
}

# ---------------------------------------------------------------------------
# Reference classification, applied to DERIVED values only.
#
# The kind decides HOW owner/identity/ref are extracted. It NEVER decides
# whether they are judged: every branch below must leave CLASS_SOURCE and
# CLASS_OWNER populated, and the single policy loop in derive_lock consults
# the allowlist for all of them without a conditional.
# ---------------------------------------------------------------------------

CLASS_KIND=''
CLASS_OWNER=''
CLASS_IDENTITY=''
CLASS_REF=''
CLASS_REF_TYPE=''
CLASS_SOURCE=''
CLASS_TARGET_REL=''

classify_reference() {
  local value="$1"
  local root="$2"
  local digest spec imageref ref lastseg
  CLASS_KIND=''; CLASS_OWNER=''; CLASS_IDENTITY=''
  CLASS_REF=''; CLASS_REF_TYPE=''; CLASS_SOURCE=''; CLASS_TARGET_REL=''

  [[ -n "$value" ]] || { reject invalid_lock_or_manifest 'empty-uses-value'; return 1; }

  if [[ "$value" == docker://* ]]; then
    CLASS_KIND='docker'
    CLASS_SOURCE='container-registry'
    spec="${value#docker://}"
    [[ -n "$spec" ]] || { reject invalid_lock_or_manifest 'empty-docker-reference'; return 1; }
    if [[ "$spec" == *@* ]]; then
      imageref="${spec%%@*}"
      ref="${spec#*@}"
      if [[ "$ref" =~ ^sha256:[0-9a-f]{64}$ ]]; then
        CLASS_REF_TYPE='docker_digest'
      else
        CLASS_REF_TYPE='mutable_tag'
      fi
    else
      imageref="$spec"
      ref='latest'
      CLASS_REF_TYPE='mutable_tag'
      lastseg="${imageref##*/}"
      if [[ "$lastseg" == *:* ]]; then
        ref="${lastseg##*:}"
        imageref="${imageref%:*}"
      fi
    fi
    [[ -n "$imageref" ]] || { reject invalid_lock_or_manifest 'empty-docker-reference'; return 1; }
    docker_normalize "$imageref" || return 1
    CLASS_IDENTITY="$DOCKER_IDENTITY"
    CLASS_OWNER="$DOCKER_OWNER"
    CLASS_REF="$ref"
    return 0
  fi

  if value_is_local "$value"; then
    CLASS_KIND='local'
    CLASS_SOURCE='repository'
    CLASS_OWNER='in-tree'
    CLASS_IDENTITY="$value"
    CLASS_REF_TYPE='local_path'
    resolve_local_target "$value" "$root" || return 1
    digest="$(digest_of "$LOCAL_TARGET")" ||
      { reject source_integrity_error 'local-action-unreadable'; return 1; }
    CLASS_REF="$digest"
    CLASS_TARGET_REL="$LOCAL_TARGET_REL"
    return 0
  fi

  if [[ "$value" =~ ^([A-Za-z0-9][A-Za-z0-9._-]*)/([A-Za-z0-9][A-Za-z0-9._/-]*)@([^[:space:]]+)$ ]]; then
    CLASS_KIND='remote'
    CLASS_SOURCE='github-remote'
    CLASS_OWNER="${BASH_REMATCH[1]}"
    CLASS_IDENTITY="${value%%@*}"
    CLASS_REF="${value#*@}"
    if [[ "$CLASS_REF" =~ ^[0-9a-f]{40}$ ]]; then
      CLASS_REF_TYPE='commit_sha'
    elif [[ "$CLASS_REF" =~ ^[0-9a-f]{7,39}$ ]]; then
      CLASS_REF_TYPE='abbrev_sha'
    else
      CLASS_REF_TYPE='mutable_tag'
    fi
    return 0
  fi

  reject invalid_lock_or_manifest 'unparseable-uses-value'
  return 1
}

# THE origin gate. One function, one table, every entry. An unknown source, an
# unknown owner, an empty argument, or an empty table all fail closed.
origin_is_trusted() {
  local source="$1"
  local owner="$2"
  local record record_source record_owner rows=0
  [[ -n "$source" && -n "$owner" ]] || return 1
  while IFS= read -r record; do
    [[ -n "$record" ]] || continue
    rows=$((rows + 1))
    record_source="${record%%	*}"
    record_owner="${record##*	}"
    [[ "$record_source" != "$source" || "$record_owner" != "$owner" ]] || return 0
  done <<<"$trusted_origins"
  (( rows > 0 )) || return 1
  return 1
}

# Does the refusal detail name the control the fixture row demands? The detail
# is a colon-delimited record whose field order differs per control, so the
# test is field membership, not a prefix or a substring: a substring test would
# match `local-action-missing` inside `local-action-missing-manifest` and blur
# exactly the distinction this column exists to make.
detail_names_reason() {
  local detail="$1"
  local want="$2"
  local -a fields=()
  local field
  [[ -n "$want" ]] || return 1
  IFS=':' read -r -a fields <<<"$detail"
  for field in ${fields[@]+"${fields[@]}"}; do
    [[ "$field" != "$want" ]] || return 0
  done
  return 1
}

frozen_debt_allowance() {
  local key="$1"
  local record name count
  while IFS= read -r record; do
    [[ -n "$record" ]] || continue
    name="${record%%	*}"
    count="${record##*	}"
    if [[ "$name" == "$key" ]]; then
      printf '%s' "$count"
      return 0
    fi
  done <<<"$frozen_floating_debt"
  printf '0'
}

# ---------------------------------------------------------------------------
# Derivation
#
# derive_lock <root> <output-file> <require-live-floor>
#   Writes the complete lock text for <root> to <output-file>.
#   Returns 1 with L361_CODE set on any bound, structure or policy violation.
#
# Everything the lock contains is a function of the bytes reachable under
# <root> through the transitive closure of `uses:`. There is no input to this
# function other than those bytes and the hard-coded policy above.
# ---------------------------------------------------------------------------

DERIVE_ACTIVE_KEYS=()
DERIVE_ACTIVE_IDENT=()
DERIVE_ACTIVE_REF=()

derive_lock() {
  local root="$1"
  local out="$2"
  local require_live_floor="$3"

  local -a seeds=() files=()
  local -a queue=() enqueued=() visited=()
  local -a entry_file=() entry_line=() entry_kind=() entry_owner=()
  local -a entry_identity=() entry_ref=() entry_reftype=() entry_source=()
  local -a entry_target=() entry_linesha=()
  local -a inert_file=() inert_line=() inert_sha=()

  DERIVE_ACTIVE_KEYS=(); DERIVE_ACTIVE_IDENT=(); DERIVE_ACTIVE_REF=()

  local workflows_dir="$root/$live_required_dir"
  local root_action="$root/$live_required_file"

  # --- Phase A: seed enumeration -----------------------------------------
  # Symlinks are DECLARED and PROVED: `find -type f` would silently omit
  # them, so they are enumerated separately and rejected outright. A
  # symlinked input is a redirect of the material under test.
  local link_count=0 special_count=0 nl_lines=0 nl_zeros=0 found
  if [[ -e "$workflows_dir" || -L "$workflows_dir" ]]; then
    [[ ! -L "$workflows_dir" ]] ||
      { reject source_integrity_error 'workflows-dir-is-symlink'; return 1; }
    [[ -d "$workflows_dir" ]] ||
      { reject source_integrity_error 'workflows-dir-not-a-directory'; return 1; }
    link_count="$(find "$workflows_dir" -type l | wc -l)"
    link_count="${link_count//[[:space:]]/}"
    (( link_count == 0 )) ||
      { reject source_integrity_error "symlink-under-workflows:$link_count"; return 1; }
    special_count="$(find "$workflows_dir" ! -type d ! -type f ! -type l | wc -l)"
    special_count="${special_count//[[:space:]]/}"
    (( special_count == 0 )) ||
      { reject source_integrity_error "special-file-under-workflows:$special_count"; return 1; }
    # A newline inside a path would desynchronise the line-oriented list.
    # Two independent counts must agree; a disagreement is a hostile path.
    nl_lines="$(find "$workflows_dir" -type f | wc -l)"
    nl_lines="${nl_lines//[[:space:]]/}"
    nl_zeros="$(find "$workflows_dir" -type f -print0 | tr -cd '\000' | wc -c)"
    nl_zeros="${nl_zeros//[[:space:]]/}"
    (( nl_lines == nl_zeros )) ||
      { reject invalid_lock_or_manifest "path-newline:$nl_lines/$nl_zeros"; return 1; }
    while IFS= read -r found; do
      [[ -n "$found" ]] || continue
      seeds+=("${found#"$root/"}")
    done < <(find "$workflows_dir" -type f | sort)
    # Count assertion beside the loop's `continue`.
    (( ${#seeds[@]} == nl_lines )) ||
      { reject invalid_lock_or_manifest "workflow-enumeration-drift:${#seeds[@]}/$nl_lines"; return 1; }
  fi

  if [[ -e "$root_action" || -L "$root_action" ]]; then
    [[ ! -L "$root_action" ]] ||
      { reject source_integrity_error 'action-manifest-is-symlink'; return 1; }
    [[ -f "$root_action" ]] ||
      { reject source_integrity_error 'action-manifest-not-a-regular-file'; return 1; }
    seeds+=("$live_required_file")
  fi

  if [[ "$require_live_floor" == true ]]; then
    [[ -f "$root_action" ]] ||
      { reject source_integrity_error 'live-floor-missing-action-manifest'; return 1; }
    [[ -d "$workflows_dir" ]] ||
      { reject source_integrity_error 'live-floor-missing-workflows-dir'; return 1; }
    (( ${#seeds[@]} >= 2 )) ||
      { reject invalid_lock_or_manifest "live-floor-seed-count:${#seeds[@]}"; return 1; }
  fi

  # Both-empty is an explicit FAILURE, never a silent success.
  (( ${#seeds[@]} > 0 )) ||
    { reject invalid_lock_or_manifest 'no-input-files'; return 1; }
  (( ${#seeds[@]} <= max_input_files )) ||
    { reject input_limit_exceeded "input-files:${#seeds[@]}"; return 1; }

  local unique_seeds
  unique_seeds="$(printf '%s\n' "${seeds[@]}" | sort -u | wc -l)"
  unique_seeds="${unique_seeds//[[:space:]]/}"
  (( unique_seeds == ${#seeds[@]} )) ||
    { reject invalid_lock_or_manifest "seed-duplicate:${#seeds[@]}/$unique_seeds"; return 1; }

  # --- Phase B: transitive closure over local `uses:` ---------------------
  # The worklist starts at the seeds and grows with every local action
  # manifest reached from any scanned file, to a fixed point. Cycle
  # detection is structural: a path already ENQUEUED is never enqueued
  # again, so `A -> B -> A` terminates; and a path being dequeued twice is
  # a hard reject rather than a silent second visit.
  local head=0 rel abs bytes nul cr i value target_rel
  local total_bytes=0 local_seen local_expected
  queue=("${seeds[@]}")
  enqueued=("${seeds[@]}")

  while (( head < ${#queue[@]} )); do
    rel="${queue[head]}"
    head=$((head + 1))
    ! array_contains "$rel" ${visited[@]+"${visited[@]}"} ||
      { reject invalid_lock_or_manifest "closure-revisit:$rel"; return 1; }
    visited+=("$rel")
    (( ${#visited[@]} <= max_input_files )) ||
      { reject input_limit_exceeded "closure-files:${#visited[@]}"; return 1; }

    abs="$root/$rel"
    bytes="$(byte_size_of "$abs")" ||
      { reject source_integrity_error "unreadable:$rel"; return 1; }
    total_bytes=$((total_bytes + bytes))
    (( total_bytes <= max_input_bytes )) ||
      { reject input_limit_exceeded "input-bytes:$total_bytes"; return 1; }
    nul="$(count_nul_bytes "$abs")"
    (( nul == 0 )) ||
      { reject invalid_lock_or_manifest "nul-byte:$rel:$nul"; return 1; }
    cr="$(count_cr_bytes "$abs")"
    (( cr == 0 )) ||
      { reject invalid_lock_or_manifest "carriage-return:$rel:$cr"; return 1; }

    scan_file "$abs" "$rel" || return 1

    # Independent count of local values on this file, computed before the
    # walk, so the walk's own `continue` cannot silently drop one.
    local_expected=0
    for (( i = 0; i < ${#FILE_VALUES[@]}; i++ )); do
      ! value_is_local "${FILE_VALUES[i]}" || local_expected=$((local_expected + 1))
    done
    local_seen=0
    for (( i = 0; i < ${#FILE_VALUES[@]}; i++ )); do
      value="${FILE_VALUES[i]}"
      value_is_local "$value" || continue
      local_seen=$((local_seen + 1))
      resolve_local_target "$value" "$root" ||
        { L361_DETAIL="$rel:${FILE_LINES[i]}:$L361_DETAIL"; return 1; }
      target_rel="$LOCAL_TARGET_REL"
      ! array_contains "$target_rel" ${enqueued[@]+"${enqueued[@]}"} || continue
      enqueued+=("$target_rel")
      queue+=("$target_rel")
    done
    (( local_seen == local_expected )) ||
      { reject invalid_lock_or_manifest "closure-local-drift:$rel:$local_seen/$local_expected"; return 1; }
  done

  # Fixed point reached. All three counts must agree or the closure is a lie.
  (( head == ${#queue[@]} )) ||
    { reject invalid_lock_or_manifest "closure-not-drained:$head/${#queue[@]}"; return 1; }
  (( ${#visited[@]} == ${#queue[@]} )) ||
    { reject invalid_lock_or_manifest "closure-visit-drift:${#visited[@]}/${#queue[@]}"; return 1; }
  (( ${#visited[@]} == ${#enqueued[@]} )) ||
    { reject invalid_lock_or_manifest "closure-fixpoint-drift:${#visited[@]}/${#enqueued[@]}"; return 1; }
  (( ${#visited[@]} >= ${#seeds[@]} )) ||
    { reject invalid_lock_or_manifest "closure-below-seeds:${#visited[@]}/${#seeds[@]}"; return 1; }
  (( ${#visited[@]} > 0 )) ||
    { reject invalid_lock_or_manifest 'no-input-files'; return 1; }
  (( ${#visited[@]} <= max_input_files )) ||
    { reject input_limit_exceeded "input-files:${#visited[@]}"; return 1; }

  mapfile -t files < <(printf '%s\n' "${visited[@]}" | sort)
  (( ${#files[@]} == ${#visited[@]} )) ||
    { reject invalid_lock_or_manifest "closure-sort-drift:${#files[@]}/${#visited[@]}"; return 1; }

  # --- Phase C: entries over the CLOSED file set --------------------------
  local idx scanned=0
  for rel in "${files[@]}"; do
    abs="$root/$rel"
    scan_file "$abs" "$rel" || return 1
    scanned=$((scanned + 1))
    for (( i = 0; i < ${#FILE_INERT_LINES[@]}; i++ )); do
      inert_file+=("$rel")
      inert_line+=("${FILE_INERT_LINES[i]}")
      inert_sha+=("${FILE_INERT_SHA[i]}")
    done
    for (( i = 0; i < ${#FILE_VALUES[@]}; i++ )); do
      classify_reference "${FILE_VALUES[i]}" "$root" ||
        { L361_DETAIL="$rel:${FILE_LINES[i]}:$L361_DETAIL"; return 1; }
      entry_file+=("$rel")
      entry_line+=("${FILE_LINES[i]}")
      entry_kind+=("$CLASS_KIND")
      entry_owner+=("$CLASS_OWNER")
      entry_identity+=("$CLASS_IDENTITY")
      entry_ref+=("$CLASS_REF")
      entry_reftype+=("$CLASS_REF_TYPE")
      entry_source+=("$CLASS_SOURCE")
      entry_target+=("$CLASS_TARGET_REL")
      entry_linesha+=("${FILE_LINE_SHA[i]}")
      (( ${#entry_file[@]} <= max_entries )) ||
        { reject input_limit_exceeded "entries:${#entry_file[@]}"; return 1; }
    done
  done
  (( scanned == ${#files[@]} )) ||
    { reject invalid_lock_or_manifest "entry-scan-drift:$scanned/${#files[@]}"; return 1; }

  # --- emptiness is failure ---------------------------------------------
  (( ${#entry_file[@]} > 0 )) ||
    { reject invalid_lock_or_manifest 'zero-uses-sites-derived'; return 1; }
  (( ${#entry_file[@]} <= max_entries )) ||
    { reject input_limit_exceeded "entries:${#entry_file[@]}"; return 1; }

  # --- closure completeness, proved from the entries themselves ----------
  # An independent second opinion on Phase B: every local entry must point at
  # a file that is IN the closed set. If the closure had missed an edge, this
  # refuses instead of passing quietly. The two counters use two different
  # predicates (non-empty resolved target vs kind == local) on purpose.
  local closure_local=0 closure_local_expected=0
  for (( idx = 0; idx < ${#entry_kind[@]}; idx++ )); do
    [[ "${entry_kind[idx]}" != 'local' ]] || closure_local_expected=$((closure_local_expected + 1))
  done
  for (( idx = 0; idx < ${#entry_target[@]}; idx++ )); do
    [[ -n "${entry_target[idx]}" ]] || continue
    closure_local=$((closure_local + 1))
    array_contains "${entry_target[idx]}" "${files[@]}" ||
      { reject source_integrity_error "closure-incomplete:${entry_file[idx]}:${entry_line[idx]}:${entry_target[idx]}"; return 1; }
  done
  (( closure_local == closure_local_expected )) ||
    { reject invalid_lock_or_manifest "closure-local-entry-drift:$closure_local/$closure_local_expected"; return 1; }

  if [[ "$require_live_floor" == true ]]; then
    local in_action=0 in_workflows=0
    for (( idx = 0; idx < ${#entry_file[@]}; idx++ )); do
      if [[ "${entry_file[idx]}" == "$live_required_file" ]]; then
        in_action=$((in_action + 1))
      elif [[ "${entry_file[idx]}" == "$live_required_dir/"* ]]; then
        in_workflows=$((in_workflows + 1))
      fi
    done
    (( in_action > 0 )) ||
      { reject invalid_lock_or_manifest 'live-floor-no-uses-in-action-manifest'; return 1; }
    (( in_workflows > 0 )) ||
      { reject invalid_lock_or_manifest 'live-floor-no-uses-in-workflows'; return 1; }
  fi

  # --- ONE policy over DERIVED entries, no branch on kind ----------------
  # There is deliberately no `if kind == ...` anywhere in this loop. The
  # origin gate runs for entry 0..N-1 unconditionally and counts itself; the
  # count assertion below turns "the check did not run" into a typed refusal
  # rather than a pass.
  local -a debt_seen_key=() debt_seen_count=()
  local key found i2 allowance
  local origin_checked=0 reftype_checked=0
  for (( idx = 0; idx < ${#entry_file[@]}; idx++ )); do
    origin_is_trusted "${entry_source[idx]}" "${entry_owner[idx]}" ||
      { reject source_integrity_error "untrusted-origin:${entry_file[idx]}:${entry_line[idx]}:${entry_source[idx]}:${entry_owner[idx]}"; return 1; }
    origin_checked=$((origin_checked + 1))

    case "${entry_reftype[idx]}" in
      commit_sha|docker_digest|local_path) ;;
      abbrev_sha)
        reject action_ref_mutable "abbreviated-sha:${entry_file[idx]}:${entry_line[idx]}:${entry_identity[idx]}@${entry_ref[idx]}"
        return 1
        ;;
      mutable_tag)
        key="${entry_identity[idx]}@${entry_ref[idx]}"
        found=-1
        for (( i2 = 0; i2 < ${#debt_seen_key[@]}; i2++ )); do
          [[ "${debt_seen_key[i2]}" != "$key" ]] || { found=$i2; break; }
        done
        if (( found < 0 )); then
          debt_seen_key+=("$key")
          debt_seen_count+=(1)
          found=$(( ${#debt_seen_key[@]} - 1 ))
        else
          debt_seen_count[found]=$(( debt_seen_count[found] + 1 ))
        fi
        allowance="$(frozen_debt_allowance "$key")"
        (( debt_seen_count[found] <= allowance )) ||
          { reject action_ref_mutable "floating-ref:${entry_file[idx]}:${entry_line[idx]}:$key:seen=${debt_seen_count[found]}:allowed=$allowance"; return 1; }
        ;;
      *)
        reject invalid_lock_or_manifest "unknown-ref-type:${entry_reftype[idx]}"
        return 1
        ;;
    esac
    reftype_checked=$((reftype_checked + 1))

    DERIVE_ACTIVE_KEYS+=("${entry_file[idx]}:${entry_line[idx]}")
    DERIVE_ACTIVE_IDENT+=("${entry_identity[idx]}")
    DERIVE_ACTIVE_REF+=("${entry_ref[idx]}")
  done
  (( origin_checked == ${#entry_file[@]} )) ||
    { reject invalid_lock_or_manifest "origin-policy-drift:$origin_checked/${#entry_file[@]}"; return 1; }
  (( reftype_checked == ${#entry_file[@]} )) ||
    { reject invalid_lock_or_manifest "reftype-policy-drift:$reftype_checked/${#entry_file[@]}"; return 1; }
  (( origin_checked > 0 )) ||
    { reject invalid_lock_or_manifest 'origin-policy-never-ran'; return 1; }
  (( ${#DERIVE_ACTIVE_KEYS[@]} == ${#entry_file[@]} )) ||
    { reject invalid_lock_or_manifest 'policy-loop-drift'; return 1; }

  # --- emission ----------------------------------------------------------
  local origin_label
  {
    printf '# GENERATED by tests/acceptance/AUR-361.sh --generate. Do not hand-edit.\n'
    printf '# Every field below is derived from the bytes of the scanned inputs.\n'
    printf 'schema: bootstrap-lock-v1\n'
    printf 'card: AUR-361\n'
    printf 'derivation: uses-closure-derived-v2\n'
    printf 'seed_file_count: %d\n' "${#seeds[@]}"
    printf 'file_count: %d\n' "${#files[@]}"
    printf 'input_bytes: %d\n' "$total_bytes"
    printf 'origin_policy_checked: %d\n' "$origin_checked"
    for (( idx = 0; idx < ${#files[@]}; idx++ )); do
      origin_label='closure'
      ! array_contains "${files[idx]}" "${seeds[@]}" || origin_label='seed'
      printf 'file_%03d_path: %s\n' "$((idx + 1))" "${files[idx]}"
      printf 'file_%03d_origin: %s\n' "$((idx + 1))" "$origin_label"
      printf 'file_%03d_bytes: %s\n' "$((idx + 1))" "$(byte_size_of "$root/${files[idx]}")"
      printf 'file_%03d_digest: %s\n' "$((idx + 1))" "$(digest_of "$root/${files[idx]}")"
    done
    printf 'active_site_count: %d\n' "${#entry_file[@]}"
    printf 'inert_line_count: %d\n' "${#inert_file[@]}"
    for (( idx = 0; idx < ${#entry_file[@]}; idx++ )); do
      printf 'entry_%03d_file: %s\n' "$((idx + 1))" "${entry_file[idx]}"
      printf 'entry_%03d_line: %s\n' "$((idx + 1))" "${entry_line[idx]}"
      printf 'entry_%03d_kind: %s\n' "$((idx + 1))" "${entry_kind[idx]}"
      printf 'entry_%03d_source: %s\n' "$((idx + 1))" "${entry_source[idx]}"
      printf 'entry_%03d_owner: %s\n' "$((idx + 1))" "${entry_owner[idx]}"
      printf 'entry_%03d_identity: %s\n' "$((idx + 1))" "${entry_identity[idx]}"
      printf 'entry_%03d_ref: %s\n' "$((idx + 1))" "${entry_ref[idx]}"
      printf 'entry_%03d_ref_type: %s\n' "$((idx + 1))" "${entry_reftype[idx]}"
      printf 'entry_%03d_target: %s\n' "$((idx + 1))" "${entry_target[idx]:--}"
      printf 'entry_%03d_line_digest: %s\n' "$((idx + 1))" "${entry_linesha[idx]}"
    done
    for (( idx = 0; idx < ${#inert_file[@]}; idx++ )); do
      printf 'inert_%03d_file: %s\n' "$((idx + 1))" "${inert_file[idx]}"
      printf 'inert_%03d_line: %s\n' "$((idx + 1))" "${inert_line[idx]}"
      printf 'inert_%03d_line_digest: %s\n' "$((idx + 1))" "${inert_sha[idx]}"
    done
  } >"$out"
  return 0
}

# ---------------------------------------------------------------------------
# Drift classification. Runs ONLY after the byte comparison has already
# decided the exit code. It selects a label; it can never select a pass.
# It keys on (file, line) so a repeated identity elsewhere in the same file
# cannot blur the label.
# ---------------------------------------------------------------------------

classify_drift() {
  local committed="$1"
  local -a ck=() ci=() cr=()
  local n idx i key ident ref found

  n="$(sed -n 's/^active_site_count: \([0-9][0-9]*\)$/\1/p' "$committed" | head -n 1)"
  [[ -n "$n" ]] || { printf 'invalid_lock_or_manifest'; return 0; }
  for (( idx = 1; idx <= n; idx++ )); do
    local pfx
    pfx="$(printf 'entry_%03d' "$idx")"
    local f l
    f="$(sed -n "s/^${pfx}_file: \(.*\)$/\1/p" "$committed" | head -n 1)"
    l="$(sed -n "s/^${pfx}_line: \(.*\)$/\1/p" "$committed" | head -n 1)"
    ident="$(sed -n "s/^${pfx}_identity: \(.*\)$/\1/p" "$committed" | head -n 1)"
    ref="$(sed -n "s/^${pfx}_ref: \(.*\)$/\1/p" "$committed" | head -n 1)"
    [[ -n "$f" && -n "$l" ]] || { printf 'invalid_lock_or_manifest'; return 0; }
    ck+=("$f:$l"); ci+=("$ident"); cr+=("$ref")
  done

  for (( i = 0; i < ${#DERIVE_ACTIVE_KEYS[@]}; i++ )); do
    key="${DERIVE_ACTIVE_KEYS[i]}"
    found=-1
    for (( idx = 0; idx < ${#ck[@]}; idx++ )); do
      [[ "${ck[idx]}" != "$key" ]] || { found=$idx; break; }
    done
    (( found >= 0 )) || continue
    [[ "${ci[found]}" == "${DERIVE_ACTIVE_IDENT[i]}" ]] || { printf 'action-identity-mismatch'; return 0; }
  done
  for (( i = 0; i < ${#DERIVE_ACTIVE_KEYS[@]}; i++ )); do
    key="${DERIVE_ACTIVE_KEYS[i]}"
    found=-1
    for (( idx = 0; idx < ${#ck[@]}; idx++ )); do
      [[ "${ck[idx]}" != "$key" ]] || { found=$idx; break; }
    done
    (( found >= 0 )) || continue
    [[ "${cr[found]}" == "${DERIVE_ACTIVE_REF[i]}" ]] || { printf 'action-ref-mutable'; return 0; }
  done
  for (( i = 0; i < ${#DERIVE_ACTIVE_KEYS[@]}; i++ )); do
    key="${DERIVE_ACTIVE_KEYS[i]}"
    found=-1
    for (( idx = 0; idx < ${#ck[@]}; idx++ )); do
      [[ "${ck[idx]}" != "$key" ]] || { found=$idx; break; }
    done
    (( found >= 0 )) || { printf 'action-unlocked'; return 0; }
  done
  for (( idx = 0; idx < ${#ck[@]}; idx++ )); do
    found=-1
    for (( i = 0; i < ${#DERIVE_ACTIVE_KEYS[@]}; i++ )); do
      [[ "${DERIVE_ACTIVE_KEYS[i]}" != "${ck[idx]}" ]] || { found=$i; break; }
    done
    (( found >= 0 )) || { printf 'action-unlocked'; return 0; }
  done
  printf 'source_integrity_error'
  return 0
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

selector="${1:-AC-001}"
case "$selector" in
  AC-001|ContractAUR361|IntegrationAUR361|E2EAUR361) ;;
  --generate)
    tmp_root="$(mktemp -d "${TMPDIR:-/tmp}/aur361.XXXXXX")"
    trap 'rm -rf -- "$tmp_root"' EXIT
    if ! derive_lock "$repo_root" "$tmp_root/derived" true; then
      fail "$L361_CODE" "$L361_DETAIL"
    fi
    mkdir -p -- "$(dirname -- "$repo_root/$lock_path")"
    cat -- "$tmp_root/derived" >"$repo_root/$lock_path"
    chmod 0644 -- "$repo_root/$lock_path"
    printf 'AUR-361: regenerated %s (%s)\n' "$lock_path" "$(digest_of "$repo_root/$lock_path")"
    exit 0
    ;;
  *) printf '%s/%s/unknown-selector\n' "$card" "$scenario" >&2; exit 64 ;;
esac

tmp_root="$(mktemp -d "${TMPDIR:-/tmp}/aur361.XXXXXX")"
trap 'rm -rf -- "$tmp_root"' EXIT

# --- Phase 0: every declared path is present and actually read -------------
declared_paths=("$lock_path" "$fixture_dir" "$self_path" "$spec_path")
declared_read_bytes=0
declared_checked=0
for declared in "${declared_paths[@]}"; do
  target="$repo_root/$declared"
  [[ -e "$target" ]] || fail invalid_lock_or_manifest "declared-path-missing:$declared"
  [[ ! -L "$target" ]] || fail source_integrity_error "declared-path-is-symlink:$declared"
  if [[ -d "$target" ]]; then
    inner=0
    while IFS= read -r found; do
      [[ -n "$found" ]] || continue
      inner=$((inner + 1))
      declared_read_bytes=$((declared_read_bytes + $(byte_size_of "$found")))
    done < <(find "$target" -type f | sort)
    (( inner > 0 )) || fail invalid_lock_or_manifest "declared-path-empty:$declared"
  else
    b="$(byte_size_of "$target")"
    (( b > 0 )) || fail invalid_lock_or_manifest "declared-path-empty:$declared"
    declared_read_bytes=$((declared_read_bytes + b))
  fi
  declared_checked=$((declared_checked + 1))
done
(( declared_checked == ${#declared_paths[@]} )) ||
  fail invalid_lock_or_manifest "declared-path-loop-drift:$declared_checked"
(( declared_read_bytes > 0 )) ||
  fail invalid_lock_or_manifest 'declared-paths-read-zero-bytes'

# --- Phase 1: regenerate the whole lock and compare byte for byte ----------
if ! derive_lock "$repo_root" "$tmp_root/derived.lock" true; then
  fail "$L361_CODE" "$L361_DETAIL"
fi
derived_digest="$(digest_of "$tmp_root/derived.lock")"
committed_digest="$(digest_of "$repo_root/$lock_path")"
if ! cmp -s -- "$tmp_root/derived.lock" "$repo_root/$lock_path"; then
  drift_label="$(classify_drift "$repo_root/$lock_path")"
  fail "$drift_label" "lock-not-derived:committed=$committed_digest:derived=$derived_digest"
fi
[[ "$derived_digest" == "$committed_digest" ]] ||
  fail source_integrity_error "digest-disagrees-with-cmp:$committed_digest:$derived_digest"

# --- Phase 1b: the origin gate really ran, once per live entry -------------
# Positive control against "the check silently did not happen": the committed
# lock records how many times the single origin gate fired, and that number
# must equal the active site count, which must itself be non-zero.
live_active="$(sed -n 's/^active_site_count: \([0-9][0-9]*\)$/\1/p' "$repo_root/$lock_path" | head -n 1)"
live_checked="$(sed -n 's/^origin_policy_checked: \([0-9][0-9]*\)$/\1/p' "$repo_root/$lock_path" | head -n 1)"
[[ -n "$live_active" && -n "$live_checked" ]] ||
  fail invalid_lock_or_manifest 'lock-missing-policy-counters'
(( live_active > 0 )) ||
  fail invalid_lock_or_manifest "live-active-sites-zero:$live_active"
(( live_checked == live_active )) ||
  fail invalid_lock_or_manifest "live-origin-policy-drift:$live_checked/$live_active"

# --- Phase 2: fixture suite against hand-written expectations --------------
cases_file="$repo_root/$fixture_dir/cases.tsv"
[[ -f "$cases_file" && ! -L "$cases_file" ]] || fail invalid_lock_or_manifest 'cases-tsv-missing'
declared_rows="$(sed -n '/^[^#]/p' "$cases_file" | sed '/^$/d' | wc -l)"
declared_rows="${declared_rows//[[:space:]]/}"
(( declared_rows > 0 )) || fail invalid_lock_or_manifest 'cases-tsv-empty'

executed=0
reason_asserted=0
refusals_expected=0
while IFS=$'\t' read -r case_name want_exit want_code want_active want_inert want_idents want_reason; do
  [[ -n "$case_name" ]] || continue
  [[ "${case_name:0:1}" != '#' ]] || continue
  executed=$((executed + 1))
  # A row may not opt out of naming its control: a refusing row must carry a
  # reason and a passing row must not, or the column would be decoration that
  # a future edit could quietly empty.
  if [[ "$want_exit" == '1' ]]; then
    refusals_expected=$((refusals_expected + 1))
    [[ -n "$want_reason" && "$want_reason" != '-' ]] ||
      fail invalid_lock_or_manifest "fixture-reason-missing:$case_name"
  else
    [[ "$want_reason" == '-' ]] ||
      fail invalid_lock_or_manifest "fixture-reason-unexpected:$case_name:$want_reason"
  fi
  case_root="$repo_root/$fixture_dir/cases/$case_name"
  [[ -d "$case_root" ]] || fail invalid_lock_or_manifest "fixture-case-missing:$case_name"
  L361_CODE=''; L361_DETAIL=''
  if derive_lock "$case_root" "$tmp_root/case.lock" false; then
    got_exit=0; got_code='pass'
  else
    got_exit=1; got_code="$L361_CODE"
  fi
  [[ "$got_exit" == "$want_exit" ]] ||
    fail invalid_lock_or_manifest "fixture-exit:$case_name:want=$want_exit:got=$got_exit:code=$got_code"
  [[ "$got_code" == "$want_code" ]] ||
    fail invalid_lock_or_manifest "fixture-code:$case_name:want=$want_code:got=$got_code:$L361_DETAIL"
  if (( got_exit == 1 )); then
    detail_names_reason "$L361_DETAIL" "$want_reason" ||
      fail invalid_lock_or_manifest "fixture-reason:$case_name:want=$want_reason:detail=$L361_DETAIL"
    reason_asserted=$((reason_asserted + 1))
  fi
  if (( got_exit == 0 )); then
    got_active="$(sed -n 's/^active_site_count: \([0-9][0-9]*\)$/\1/p' "$tmp_root/case.lock" | head -n 1)"
    got_inert="$(sed -n 's/^inert_line_count: \([0-9][0-9]*\)$/\1/p' "$tmp_root/case.lock" | head -n 1)"
    got_checked="$(sed -n 's/^origin_policy_checked: \([0-9][0-9]*\)$/\1/p' "$tmp_root/case.lock" | head -n 1)"
    got_idents="$(sed -n 's/^entry_[0-9][0-9][0-9]_identity: \(.*\)$/\1/p' "$tmp_root/case.lock" | sort -u | tr '\n' ',' )"
    got_idents="${got_idents%,}"
    [[ "$got_active" == "$want_active" ]] ||
      fail invalid_lock_or_manifest "fixture-active:$case_name:want=$want_active:got=$got_active"
    [[ "$got_inert" == "$want_inert" ]] ||
      fail invalid_lock_or_manifest "fixture-inert:$case_name:want=$want_inert:got=$got_inert"
    [[ "$got_idents" == "$want_idents" ]] ||
      fail invalid_lock_or_manifest "fixture-identities:$case_name:want=$want_idents:got=$got_idents"
    # Same positive control as the live tree: a passing fixture must show the
    # origin gate firing once per active site, never zero.
    [[ "$got_checked" == "$got_active" ]] ||
      fail invalid_lock_or_manifest "fixture-origin-policy-drift:$case_name:$got_checked/$got_active"
  fi
done < <(sed -n '/^[^#]/p' "$cases_file" | sed '/^$/d')

(( executed == declared_rows )) ||
  fail invalid_lock_or_manifest "fixture-count:executed=$executed:declared=$declared_rows"
(( executed >= 36 )) ||
  fail invalid_lock_or_manifest "fixture-floor:executed=$executed"
# Count assertion beside the reason check: every expected refusal named its
# control, and there is at least one. Zero named controls is a failure, not a
# clean suite.
(( reason_asserted == refusals_expected )) ||
  fail invalid_lock_or_manifest "fixture-reason-drift:asserted=$reason_asserted:expected=$refusals_expected"
(( reason_asserted > 0 )) ||
  fail invalid_lock_or_manifest 'fixture-reason-never-asserted'

live_files="$(sed -n 's/^file_count: \([0-9][0-9]*\)$/\1/p' "$repo_root/$lock_path" | head -n 1)"
live_seeds="$(sed -n 's/^seed_file_count: \([0-9][0-9]*\)$/\1/p' "$repo_root/$lock_path" | head -n 1)"
printf '{"card":"%s","scenario":"%s","selector":"%s","lock_digest":"%s","seed_files":%s,"closure_files":%s,"active_sites":%s,"origin_checks":%s,"fixture_cases":%d,"named_controls":%d,"result":"pass"}\n' \
  "$card" "$scenario" "$selector" "$committed_digest" "$live_seeds" "$live_files" "$live_active" "$live_checked" "$executed" "$reason_asserted"
