package pipeline

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Mpaape/AurumCode/internal/documentation/extractors"
	"github.com/Mpaape/AurumCode/internal/documentation/site"
	"github.com/Mpaape/AurumCode/internal/llm"
	"github.com/Mpaape/AurumCode/internal/llm/cost"
)

// gomarkdocOutput is the markdown gomarkdoc v1.1.0 emits for a one-function
// package. It is reproduced verbatim here because gomarkdoc is not installed in
// the pinned build container: the external tool is the only part of the chain
// replaced by a double. Source discovery, language grouping, front-matter
// normalization and the site scaffold all run for real against it.
const gomarkdocOutput = "<!-- Code generated by gomarkdoc. DO NOT EDIT -->\n\n" +
	"# ledger\n\n" +
	"```go\nimport \"example.com/tinyrepo/ledger\"\n```\n\n" +
	"## Index\n\n" +
	"- [func AddMoney\\(a, b int\\) int](<#AddMoney>)\n\n" +
	"<a name=\"AddMoney\"></a>\n" +
	"## func AddMoney\n\n" +
	"```go\nfunc AddMoney(a, b int) int\n```\n\n" +
	"AddMoney sums two monetary amounts expressed in cents.\n"

// fileWritingExtractor is a stand-in for a language extractor that really puts
// markdown on disk, so the steps downstream of extraction have something to
// read. It cannot report success on its own: every assertion in this file reads
// files written by production code.
type fileWritingExtractor struct {
	lang  extractors.Language
	files map[string]string
}

func (f *fileWritingExtractor) Language() extractors.Language { return f.lang }

func (f *fileWritingExtractor) Validate(ctx context.Context) error { return nil }

func (f *fileWritingExtractor) Extract(ctx context.Context, req *extractors.ExtractRequest) (*extractors.ExtractResult, error) {
	if err := os.MkdirAll(req.OutputDir, 0o755); err != nil {
		return nil, err
	}

	result := &extractors.ExtractResult{Language: f.lang}
	for name, content := range f.files {
		path := filepath.Join(req.OutputDir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return nil, err
		}
		result.Files = append(result.Files, path)
		result.Stats.FilesProcessed++
		result.Stats.DocsGenerated++
	}

	return result, nil
}

// recordingProvider is an llm.Provider double. It only returns text; whether the
// welcome page reached disk is decided by the real welcome generator and the
// real scaffold, and asserted by reading the file.
type recordingProvider struct {
	text   string
	err    error
	prompt string
	calls  int
}

func (p *recordingProvider) Complete(prompt string, opts llm.Options) (llm.Response, error) {
	p.calls++
	p.prompt = prompt
	if p.err != nil {
		return llm.Response{}, p.err
	}
	return llm.Response{Text: p.text, TokensIn: 10, TokensOut: 20, Model: "double"}, nil
}

func (p *recordingProvider) Tokens(input string) (int, error) { return len(input) / 4, nil }

func (p *recordingProvider) Name() string { return "recording-double" }

func newScaffoldFixture(t *testing.T) (repo string, config *ExtractorPipelineConfig) {
	t.Helper()

	repo = t.TempDir()
	pkgDir := filepath.Join(repo, "ledger")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("create fixture package: %v", err)
	}

	writeSourceFile(t, pkgDir, "ledger.go", "package ledger\n\n"+
		"// AddMoney sums two monetary amounts expressed in cents.\n"+
		"func AddMoney(a, b int) int { return a + b }\n")

	outputDir := filepath.Join(repo, ".aurumcode")
	config = &ExtractorPipelineConfig{
		SourceDir: repo,
		OutputDir: outputDir,
		DocsDir:   outputDir,
	}

	return repo, config
}

func readGenerated(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("expected generated file at %s: %v", path, err)
	}
	return string(data)
}

// readGeneratedOptional is readGenerated without the fatal: AUR-484 option (b)
// means reference.md legitimately does not exist for a single-page run, and a
// caller that never reads its "reference" return value must not fail on that.
func readGeneratedOptional(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

// TestExtractorPipeline_Run_WithoutLLMProducesServableSite pins the promise the
// action makes: a run with no LLM provider at all still has to leave behind
// something GitHub Pages can serve. Markdown alone is not a site - without
// index.md the published root is a 404 and without _config.yml the .md files
// are served as downloads instead of pages.
func TestExtractorPipeline_Run_WithoutLLMProducesServableSite(t *testing.T) {
	_, config := newScaffoldFixture(t)

	// nil orchestrator is exactly what cmd/regenerate-docs builds when no
	// LLM_API_KEY / OPENAI_API_KEY is present.
	pipeline := NewExtractorPipeline(config, site.NewMockRunner(), nil)
	if err := pipeline.RegisterExtractor(&fileWritingExtractor{
		lang:  extractors.LanguageGo,
		files: map[string]string{"ledger.md": gomarkdocOutput},
	}); err != nil {
		t.Fatalf("RegisterExtractor failed: %v", err)
	}

	if err := pipeline.Run(context.Background()); err != nil {
		t.Fatalf("Run without an LLM provider must succeed: %v", err)
	}

	indexPath := filepath.Join(config.DocsDir, "index.md")
	configPath := filepath.Join(config.DocsDir, "_config.yml")

	if _, err := os.Stat(indexPath); err != nil {
		t.Fatalf("no index.md was generated: the published site root would be a 404 (%v)", err)
	}
	if _, err := os.Stat(configPath); err != nil {
		t.Fatalf("no _config.yml was generated: Jekyll would not render the markdown (%v)", err)
	}

	index := readGenerated(t, indexPath)

	// AUR-484 option (b): a single-page run writes no reference.md - the
	// page's own link is inlined directly into index.md instead (see
	// renderPageSummaryBlock's len(pages)==1 case).
	if !strings.HasPrefix(index, "---\n") || !strings.Contains(index, "layout: default") {
		t.Errorf("index.md has no Jekyll front matter:\n%s", index)
	}
	if !strings.Contains(index, "/go/ledger/") {
		t.Errorf("index.md does not link to the generated go/ledger page:\n%s", index)
	}
	if strings.Contains(index, "no documentation") {
		t.Errorf("index.md claims nothing was documented although go/ledger.md exists:\n%s", index)
	}

	siteConfig := readGenerated(t, configPath)
	if !strings.Contains(siteConfig, "title:") {
		t.Errorf("_config.yml has no site title:\n%s", siteConfig)
	}
}

// TestExtractorPipeline_Run_ScaffoldIsIdempotent pins that running twice over
// the same output directory does not duplicate the generated section.
func TestExtractorPipeline_Run_ScaffoldIsIdempotent(t *testing.T) {
	_, config := newScaffoldFixture(t)

	newRun := func() {
		pipeline := NewExtractorPipeline(config, site.NewMockRunner(), nil)
		if err := pipeline.RegisterExtractor(&fileWritingExtractor{
			lang:  extractors.LanguageGo,
			files: map[string]string{"ledger.md": gomarkdocOutput},
		}); err != nil {
			t.Fatalf("RegisterExtractor failed: %v", err)
		}
		if err := pipeline.Run(context.Background()); err != nil {
			t.Fatalf("Run failed: %v", err)
		}
	}

	newRun()
	first := readGenerated(t, filepath.Join(config.DocsDir, "index.md"))
	newRun()
	second := readGenerated(t, filepath.Join(config.DocsDir, "index.md"))

	if first != second {
		t.Errorf("a second run rewrote index.md differently:\nfirst:\n%s\nsecond:\n%s", first, second)
	}
	if strings.Count(second, "AddMoney") != strings.Count(first, "AddMoney") {
		t.Errorf("the generated symbol list was duplicated:\n%s", second)
	}
}

// TestExtractorPipeline_Run_WithLLMKeepsWelcomeAndPageIndex proves the welcome
// page stays an enrichment rather than a replacement: with a provider
// configured the LLM prose has to survive into index.md, and the deterministic
// page listing has to survive next to it.
func TestExtractorPipeline_Run_WithLLMKeepsWelcomeAndPageIndex(t *testing.T) {
	repo, config := newScaffoldFixture(t)
	config.GenerateWelcome = true

	writeSourceFile(t, repo, "README.md", "# tinyrepo\n\nA ledger.\n")

	const welcomeProse = "Welcome to the tinyrepo ledger documentation."
	provider := &recordingProvider{text: "# tinyrepo\n\n" + welcomeProse + "\n"}
	orchestrator := llm.NewOrchestrator(provider, nil, cost.NewTracker(10, 10, map[string]cost.PriceMap{}))

	pipeline := NewExtractorPipeline(config, site.NewMockRunner(), orchestrator)
	if err := pipeline.RegisterExtractor(&fileWritingExtractor{
		lang:  extractors.LanguageGo,
		files: map[string]string{"ledger.md": gomarkdocOutput},
	}); err != nil {
		t.Fatalf("RegisterExtractor failed: %v", err)
	}

	if err := pipeline.Run(context.Background()); err != nil {
		t.Fatalf("Run with an LLM provider must succeed: %v", err)
	}

	if provider.calls == 0 {
		t.Fatal("the welcome path never reached the provider")
	}

	index := readGenerated(t, filepath.Join(config.DocsDir, "index.md"))

	// AUR-484 option (b): single page, so its link is inlined into index.md,
	// no reference.md is written.
	if !strings.Contains(index, welcomeProse) {
		t.Errorf("the LLM welcome prose was dropped from index.md:\n%s", index)
	}
	if !strings.Contains(index, "/go/ledger/") {
		t.Errorf("the deterministic page link was dropped from index.md:\n%s", index)
	}
	if _, err := os.Stat(filepath.Join(config.DocsDir, "_config.yml")); err != nil {
		t.Errorf("_config.yml must exist regardless of the welcome page: %v", err)
	}
}

// TestExtractorPipeline_Run_WelcomeFailureKeepsDeterministicIndex pins the
// degradation floor of the enrichment: a provider that errors must not cost the
// run its index page.
func TestExtractorPipeline_Run_WelcomeFailureKeepsDeterministicIndex(t *testing.T) {
	repo, config := newScaffoldFixture(t)
	config.GenerateWelcome = true

	writeSourceFile(t, repo, "README.md", "# tinyrepo\n")

	provider := &recordingProvider{err: errors.New("provider is down")}
	orchestrator := llm.NewOrchestrator(provider, nil, cost.NewTracker(10, 10, map[string]cost.PriceMap{}))

	pipeline := NewExtractorPipeline(config, site.NewMockRunner(), orchestrator)
	if err := pipeline.RegisterExtractor(&fileWritingExtractor{
		lang:  extractors.LanguageGo,
		files: map[string]string{"ledger.md": gomarkdocOutput},
	}); err != nil {
		t.Fatalf("RegisterExtractor failed: %v", err)
	}

	if err := pipeline.Run(context.Background()); err != nil {
		t.Fatalf("a failed welcome page must not fail the run: %v", err)
	}

	// AUR-484 option (b): single page, so its link is inlined into index.md.
	index := readGenerated(t, filepath.Join(config.DocsDir, "index.md"))
	if !strings.Contains(index, "/go/ledger/") {
		t.Errorf("index.md must still link the documented page after a welcome failure:\n%s", index)
	}
}

// TestExtractorPipeline_Run_NoSourceFilesStillScaffoldsSite pins the same floor
// for a repository the pipeline finds nothing to document in: returning early
// without a scaffold publishes a 404 at the site root while the run exits 0.
func TestExtractorPipeline_Run_NoSourceFilesStillScaffoldsSite(t *testing.T) {
	repo, config := newScaffoldFixture(t)
	if err := os.RemoveAll(filepath.Join(repo, "ledger")); err != nil {
		t.Fatalf("empty the fixture: %v", err)
	}

	pipeline := NewExtractorPipeline(config, site.NewMockRunner(), nil)
	if err := pipeline.Run(context.Background()); err != nil {
		t.Fatalf("Run over a repository with no supported sources must succeed: %v", err)
	}

	if _, err := os.Stat(filepath.Join(config.DocsDir, "index.md")); err != nil {
		t.Fatalf("no index.md: the published root would be a 404 (%v)", err)
	}
	if _, err := os.Stat(filepath.Join(config.DocsDir, "_config.yml")); err != nil {
		t.Fatalf("no _config.yml: the pages would not be rendered (%v)", err)
	}
}
