package grammar

import (
	"bytes"
	"strings"
	"unicode/utf8"
)

// LooksBinary decides from content alone, never from a name: a NUL byte in the
// leading window, or a high share of bytes that are neither text nor valid
// UTF-8, marks the file as binary.
func LooksBinary(content []byte) bool {
	window := content
	if len(window) > 8000 {
		window = window[:8000]
	}
	if len(window) == 0 {
		return false
	}
	if bytes.IndexByte(window, 0) >= 0 {
		return true
	}
	bad := 0
	for i := 0; i < len(window); {
		r, size := utf8.DecodeRune(window[i:])
		if r == utf8.RuneError && size <= 1 {
			// A multibyte rune cut by the window edge is not evidence.
			if i >= len(window)-3 {
				break
			}
			bad++
		} else if r < 0x20 && r != '\n' && r != '\r' && r != '\t' && r != '\f' {
			bad++
		}
		i += size
	}
	return bad*10 > len(window)
}

// LooksGenerated reports a self-declared generated file: one of its first
// lines says it was generated, language-neutrally, in the file's own words.
func LooksGenerated(content []byte) bool {
	head := content
	if len(head) > 2048 {
		head = head[:2048]
	}
	lines := strings.SplitN(strings.ToLower(string(head)), "\n", 12)
	for i, ln := range lines {
		if i == len(lines)-1 && len(lines) == 12 {
			break
		}
		if strings.Contains(ln, "@generated") ||
			(strings.Contains(ln, "generated") && (strings.Contains(ln, "do not edit") || strings.Contains(ln, "do not modify"))) ||
			strings.Contains(ln, "auto-generated") || strings.Contains(ln, "autogenerated") {
			return true
		}
	}
	return false
}
