package grammar

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLanguagesEnumeratedAtRuntime(t *testing.T) {
	langs := Languages()
	if len(langs) < 100 {
		t.Fatalf("runtime should enumerate its grammars, got %d", len(langs))
	}
}

func TestCorpusStructure(t *testing.T) {
	root := filepath.Join("testdata", "corpus")
	want := map[string]bool{ // file -> expects a grammar
		"Greeter.java": true, "Greeter.cs": true, "Greeter.kt": true, "greeter.php": true,
		"greeter.rb": true, "main.tf": true, ".github/workflows/ci.yml": true, "Dockerfile": true,
		"notes.zzqx": false,
	}
	for rel, grammarExpected := range want {
		data, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Fatal(err)
		}
		s := Analyze(rel, data)
		t.Logf("%s -> lang=%s structure=%v symbols=%v imports=%v reason=%q", rel, s.Language, s.HasStructure, s.Symbols, s.Imports, s.Reason)
		if s.HasStructure != grammarExpected {
			t.Errorf("%s: HasStructure=%v want %v", rel, s.HasStructure, grammarExpected)
		}
		if !grammarExpected && s.Reason == "" {
			t.Errorf("%s: missing reason", rel)
		}
	}
}

func TestBinaryAndGenerated(t *testing.T) {
	if !LooksBinary([]byte{0x7f, 'E', 'L', 'F', 0, 1, 2}) {
		t.Fatal("NUL content must be binary")
	}
	if LooksBinary([]byte("plain text\nwith lines\n")) || LooksBinary([]byte("ação é texto utf8")) {
		t.Fatal("text is not binary")
	}
	hi := make([]byte, 400)
	for i := range hi {
		hi[i] = byte(0x80 + i%0x30)
	}
	if !LooksBinary(hi) {
		t.Fatal("high-entropy invalid utf8 must be binary even without NUL")
	}
	if !LooksGenerated([]byte("// Code generated by x. DO NOT EDIT.\npackage a\n")) {
		t.Fatal("generated marker")
	}
	if LooksGenerated([]byte("package a\n// ordinary\n")) {
		t.Fatal("not generated")
	}
}
