// Command docgen is the stand-in the end-to-end smoke test installs under the
// name "gomarkdoc" when the real tool is not on PATH. It reads the fixture
// sources with go/doc, so the rendered symbols come from the source tree and
// not from a canned string, and it rejects every argument shape the real
// gomarkdoc rejects: only "-o <file> <package>" is accepted, and the package
// argument must be a filesystem path by the go command's rules (absolute, ".",
// "./..." or "../..."), otherwise it is an import path and cannot be resolved.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 1 && args[0] == "--version" {
		fmt.Println("docgen-standin")
		return nil
	}

	if len(args) != 3 || args[0] != "-o" {
		return fmt.Errorf("unsupported invocation %q: expected -o <output> <package>", strings.Join(args, " "))
	}

	outputPath, pkgArg := args[1], args[2]
	if !isFilesystemPath(pkgArg) {
		return fmt.Errorf("invalid package at import path: %s", pkgArg)
	}

	info, err := os.Stat(pkgArg)
	if err != nil {
		return fmt.Errorf("invalid package at %s: %w", pkgArg, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("invalid package at %s: not a directory", pkgArg)
	}

	rendered, err := render(pkgArg)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}

	return os.WriteFile(outputPath, []byte(rendered), 0o644)
}

// isFilesystemPath mirrors the go command's rule for telling a directory
// pattern apart from an import path.
func isFilesystemPath(arg string) bool {
	return filepath.IsAbs(arg) ||
		arg == "." || arg == ".." ||
		strings.HasPrefix(arg, "./") || strings.HasPrefix(arg, "../")
}

func render(dir string) (string, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi fs.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return "", fmt.Errorf("parse %s: %w", dir, err)
	}
	if len(pkgs) == 0 {
		return "", fmt.Errorf("no Go package in %s", dir)
	}

	names := make([]string, 0, len(pkgs))
	for name := range pkgs {
		names = append(names, name)
	}
	sort.Strings(names)

	var out bytes.Buffer
	out.WriteString("<!-- generated by the AurumCode e2e docgen stand-in -->\n\n")

	for _, name := range names {
		docPkg := doc.New(pkgs[name], "./"+filepath.Base(dir), 0)

		fmt.Fprintf(&out, "# %s\n\n%s\n", docPkg.Name, strings.TrimSpace(docPkg.Doc))

		for _, fn := range docPkg.Funcs {
			writeSymbol(&out, fset, "func "+fn.Name, fn.Decl, fn.Doc)
		}

		for _, typ := range docPkg.Types {
			writeSymbol(&out, fset, "type "+typ.Name, typ.Decl, typ.Doc)
			for _, fn := range typ.Funcs {
				writeSymbol(&out, fset, "func "+fn.Name, fn.Decl, fn.Doc)
			}
			for _, method := range typ.Methods {
				writeSymbol(&out, fset, "method "+typ.Name+"."+method.Name, method.Decl, method.Doc)
			}
		}
	}

	return out.String(), nil
}

func writeSymbol(out *bytes.Buffer, fset *token.FileSet, heading string, decl ast.Node, docText string) {
	if fn, ok := decl.(*ast.FuncDecl); ok {
		fn.Body = nil
	}

	var signature bytes.Buffer
	if err := printer.Fprint(&signature, fset, decl); err != nil {
		signature.Reset()
		signature.WriteString(heading)
	}

	fmt.Fprintf(out, "\n## %s\n\n```go\n%s\n```\n\n%s\n",
		heading, strings.TrimSpace(signature.String()), strings.TrimSpace(docText))
}
