package unit

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

const schemaPath403 = ".board/schemas/go-unit-offline-profile.schema.json"
const profilePath403 = ".board/oci/profiles/go-unit-offline-v1.json"
const lockPath403 = ".board/locks/oci/go-unit-offline-v1.lock.json"
const registryPath403 = ".board/oci/profiles/registry.v1.json"

type profile403 struct { Schema string `json:"schema"`; Version int `json:"version"`; Profile string `json:"profile"`; Lock string `json:"lock"`; LockDigest string `json:"lock_digest"`; Network string `json:"network"`; User string `json:"user"`; CapDrop string `json:"cap_drop"`; CapAdd string `json:"cap_add"`; Mounts string `json:"mounts"`; Devices string `json:"devices"`; Pull string `json:"pull"`; Tmpfs string `json:"tmpfs"`; CheckoutReadonly bool `json:"checkout_readonly"`; ReadOnlyRootfs bool `json:"read_only_rootfs"`; NoNewPrivileges bool `json:"no_new_privileges"`; Privileged bool `json:"privileged"`; TimeoutSeconds int `json:"timeout_seconds"`; MemoryMB int `json:"memory_mb"`; CPUMillis int `json:"cpu_millis"`; PidsLimit int `json:"pids_limit"`; TmpfsMB int `json:"tmpfs_mb"`; StdoutLimitBytes int `json:"stdout_limit_bytes"`; StderrLimitBytes int `json:"stderr_limit_bytes"`; MaxInputFiles int `json:"max_input_files"`; MaxInputBytes int `json:"max_input_bytes"`; ModuleCache string `json:"module_cache"`; ModuleCacheReadOnly bool `json:"module_cache_read_only"`; Environment map[string]string `json:"environment"`; Command []string `json:"command"` }
type lock403 struct { Schema string `json:"schema"`; Version int `json:"version"`; Profile string `json:"profile"`; Image string `json:"image"` }
type entry403 struct { Key string `json:"key"`; Schema string `json:"schema"`; SchemaDigest string `json:"schema_digest"`; Lock string `json:"lock"`; LockDigest string `json:"lock_digest"`; ImageSetDigest string `json:"image_set_digest"` }
type registry403 struct { Schema string `json:"schema"`; Version int `json:"version"`; Profiles []entry403 `json:"profiles"` }

var digest403 = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)
var image403 = regexp.MustCompile(`^golang@sha256:[0-9a-f]{64}$`)
func hash403(b []byte) string { h := sha256.Sum256(b); return "sha256:" + hex.EncodeToString(h[:]) }
func decode403(b []byte, out any) error { d:=json.NewDecoder(bytes.NewReader(b)); d.DisallowUnknownFields(); if err:=d.Decode(out);err!=nil{return err}; var tail any;if d.Decode(&tail)!=io.EOF{return fmt.Errorf("trailing JSON")};return nil }
func read403(root, path string)([]byte,error){ if strings.Contains(path,"..")||strings.Contains(path,"//"){return nil,fmt.Errorf("unsafe path")};i,e:=os.Lstat(filepath.Join(root,path));if e!=nil||!i.Mode().IsRegular(){return nil,fmt.Errorf("missing")};return os.ReadFile(filepath.Join(root,path)) }

func validateProfile403(root string)(profile403,lock403,string){ sb,e:=read403(root,schemaPath403);if e!=nil{return profile403{},lock403{},"schema-missing"};pb,e:=read403(root,profilePath403);if e!=nil{return profile403{},lock403{},"profile-missing"};var p profile403;if decode403(pb,&p)!=nil{return p,lock403{},"schema-invalid"};if p.Schema!="aurum.go-unit-offline-profile"||p.Version!=1||p.Profile!="go-unit-offline-v1"||p.Lock!=lockPath403||!digest403.MatchString(p.LockDigest)||p.Network!="none"||p.User!="65534:65534"||p.CapDrop!="ALL"||p.CapAdd!="none"||p.Mounts!="none"||p.Devices!="none"||p.Pull!="never"||p.Tmpfs!="rw,nosuid,nodev"||!p.CheckoutReadonly||!p.ReadOnlyRootfs||!p.NoNewPrivileges||p.Privileged||p.TimeoutSeconds!=60||p.MemoryMB!=256||p.CPUMillis!=1000||p.PidsLimit!=128||p.TmpfsMB!=128||p.StdoutLimitBytes!=65536||p.StderrLimitBytes!=65536||p.MaxInputFiles!=10000||p.MaxInputBytes!=67108864||p.ModuleCache!="/go/pkg/mod"||!p.ModuleCacheReadOnly||p.Environment["GOPROXY"]!="off"||p.Environment["GOSUMDB"]!="off"||p.Environment["GONOSUMDB"]!="*"||p.Environment["GOTOOLCHAIN"]!="local"||len(p.Environment)!=4||strings.Join(p.Command," ")!="go test -mod=readonly ./..."{return p,lock403{},"unsafe-plan"};lb,e:=read403(root,lockPath403);if e!=nil{return p,lock403{},"lock-missing"};var l lock403;if decode403(lb,&l)!=nil||l.Schema!="aurum.oci-image-lock"||l.Version!=1||l.Profile!=p.Profile||!image403.MatchString(l.Image){return p,l,"mutable-input"};if hash403(lb)!=p.LockDigest{return p,l,"lock-digest-mismatch"};if hash403(sb)==""{return p,l,"schema-invalid"};return p,l,"valid" }
func validateRegistry403(root string)(string,string){rb,e:=read403(root,registryPath403);if e!=nil{return "","registry-missing"};var r registry403;if decode403(rb,&r)!=nil||r.Schema!="aurum.profile-registry"||r.Version!=1{return "","schema-invalid"};sb,e:=read403(root,schemaPath403);if e!=nil{return "","schema-missing"};keys:=make([]string,len(r.Profiles));seen:=map[string]bool{};for i,x:=range r.Profiles{keys[i]=x.Key;if seen[x.Key]{return "","duplicate-profile"};seen[x.Key]=true;if i>0&&keys[i-1]>=x.Key{return "","order-invalid"};if x.Key!="bootstrap-readonly-v1"&&x.Key!="go-unit-offline-v1"&&x.Key!="registry-v1"{return "","profile-unregistered"};if x.Key=="go-unit-offline-v1"{if x.Schema!=schemaPath403||x.Lock!=lockPath403{return "","unsafe-plan"};if x.SchemaDigest!=hash403(sb){return "","schema-digest-mismatch"};pb,_:=read403(root,profilePath403);if hash403(pb)==""||x.SchemaDigest==""{return "","schema-invalid"};_,l,c:=validateProfile403(root);if c!="valid"{return "",c};lb,_:=read403(root,lockPath403);if x.LockDigest!=hash403(lb)||x.ImageSetDigest!=hash403([]byte(l.Image)){return "","unsafe-plan"}}else if x.Schema!=".board/schemas/container-profile.schema.json"||x.Lock!=".board/locks/oci/registry-v1.lock.json"{return "","unsafe-plan"}else if !digest403.MatchString(x.SchemaDigest)||!digest403.MatchString(x.LockDigest)||!digest403.MatchString(x.ImageSetDigest){return "","digest-invalid"}};if len(r.Profiles)!=3||!sort.StringsAreSorted(keys)||keys[0]!="bootstrap-readonly-v1"||keys[1]!="go-unit-offline-v1"||keys[2]!="registry-v1"{return "","profile-unregistered"};return hash403(rb),"valid"}

func TestAUR403(t *testing.T){root:=os.Getenv("AURUMCODE_ROOT");if root==""{t.Fatal("AURUMCODE_ROOT is required")};mutation:=os.Getenv("AURUM_A403_MUTATION");if mutation=="mutable-input"{lb,_:=read403(root,lockPath403);lb=bytes.Replace(lb,[]byte("golang@sha256:2414035b086e3c42b99654c8b26e6f5b1b1598080d65fd03c7f499552ff4dc94"),[]byte("golang:latest"),1);if os.WriteFile(filepath.Join(root,lockPath403),lb,0600)!=nil{t.Fatal("mutate lock")};pb,_:=read403(root,profilePath403);var p map[string]any;if decode403(pb,&p)!=nil{t.Fatal("profile decode")};p["lock_digest"]=hash403(lb);nb,_:=json.Marshal(p);if os.WriteFile(filepath.Join(root,profilePath403),nb,0600)!=nil{t.Fatal("mutate profile")}};if mutation=="unsafe-plan"{pb,_:=read403(root,profilePath403);pb=bytes.Replace(pb,[]byte(`"network": "none"`),[]byte(`"network": "host"`),1);if os.WriteFile(filepath.Join(root,profilePath403),pb,0600)!=nil{t.Fatal("mutate isolation")}};if mutation=="duplicate-profile"{rb,_:=read403(root,registryPath403);var r registry403;if decode403(rb,&r)!=nil{t.Fatal("registry decode")};r.Profiles=append(r.Profiles,r.Profiles[1]);nb,_:=json.Marshal(r);if os.WriteFile(filepath.Join(root,registryPath403),nb,0600)!=nil{t.Fatal("mutate registry")}};d,c:=validateRegistry403(root);if mutation!=""{if c!=mutation{t.Fatalf("mutation %s got %s",mutation,c)};fmt.Printf("mutation=%s code=%s\n",mutation,c);return};if c!="valid"||d==""{t.Fatalf("registry result=%s/%s",c,d)};fmt.Printf("registry_digest=%s\n",d)}
