package site

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

// The generated page listing is delimited so a second run replaces it instead of
// appending a duplicate, and so hand-written or LLM-written prose above it
// survives untouched.
const (
	scaffoldBlockStart = "<!-- aurumcode:pages:start -->"
	scaffoldBlockEnd   = "<!-- aurumcode:pages:end -->"
)

// scaffoldMaxSymbols bounds how many symbols a single page contributes to the
// index. A package with hundreds of exported symbols would otherwise turn the
// landing page into a wall of text.
const scaffoldMaxSymbols = 20

// structuralHeadings are headings documentation tools emit for navigation rather
// than for a documented symbol. Listing them again on the index is noise.
var structuralHeadings = map[string]struct{}{
	"index":    {},
	"contents": {},
	"overview": {},
}

var (
	scaffoldHTMLTag      = regexp.MustCompile(`<[^>]*>`)
	scaffoldMarkdownLink = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)
	scaffoldEscape       = regexp.MustCompile("\\\\([\\\\`*_{}\\[\\]()#+\\-.!])")
	scaffoldHeading      = regexp.MustCompile(`^(#{1,6})\s+(.*)$`)
)

// ScaffoldConfig configures the deterministic site scaffold.
type ScaffoldConfig struct {
	// DocsDir is the site root: index.md and _config.yml are written there.
	DocsDir string

	// OutputDir holds the generated per-language markdown that the index lists.
	OutputDir string

	// Title and Description name the site in _config.yml and on the index page.
	Title       string
	Description string

	// BaseURL is the Jekyll baseurl, e.g. "/my-repo" for a project Pages site.
	BaseURL string
}

// ScaffoldPage is one generated documentation page as the index sees it.
type ScaffoldPage struct {
	Language string
	Title    string
	Link     string
	Symbols  []string
}

// ScaffoldResult reports what the scaffold left on disk.
type ScaffoldResult struct {
	IndexPath     string
	ConfigPath    string
	Pages         []ScaffoldPage
	ConfigCreated bool
}

// Scaffold turns a directory of generated markdown into something a static site
// host can actually serve.
//
// It exists because markdown alone is not a site: without an index.md the
// published root is a 404, and without a _config.yml the host has no reason to
// render the .md files as pages. Both files are produced deterministically from
// what is on disk, with no LLM involved, so a consumer without any provider key
// still gets a browsable site. The LLM welcome page remains an enrichment: when
// it ran, its prose is kept above the generated page listing.
type Scaffold struct {
	config ScaffoldConfig
}

// NewScaffold creates a scaffold generator.
func NewScaffold(config ScaffoldConfig) *Scaffold {
	if config.Title == "" {
		config.Title = "Documentation"
	}
	if config.Description == "" {
		config.Description = "API documentation generated by AurumCode."
	}

	return &Scaffold{config: config}
}

// Generate writes _config.yml and index.md. It is safe to run repeatedly: the
// generated page listing is replaced in place and an existing _config.yml is
// never overwritten, so a consumer can customise the site config.
func (s *Scaffold) Generate() (*ScaffoldResult, error) {
	if s.config.DocsDir == "" {
		return nil, fmt.Errorf("scaffold: DocsDir is required")
	}

	pages, err := s.collectPages()
	if err != nil {
		return nil, err
	}

	if err := os.MkdirAll(s.config.DocsDir, 0o755); err != nil {
		return nil, fmt.Errorf("scaffold: create %s: %w", s.config.DocsDir, err)
	}

	result := &ScaffoldResult{
		IndexPath:  filepath.Join(s.config.DocsDir, "index.md"),
		ConfigPath: filepath.Join(s.config.DocsDir, "_config.yml"),
		Pages:      pages,
	}

	created, err := s.writeConfig(result.ConfigPath)
	if err != nil {
		return nil, err
	}
	result.ConfigCreated = created

	if err := s.writeIndex(result.IndexPath, pages); err != nil {
		return nil, err
	}

	return result, nil
}

// collectPages reads every generated markdown page under OutputDir and records
// how the index should link to it. Only files that really exist are listed: the
// index never advertises a page that was not written.
func (s *Scaffold) collectPages() ([]ScaffoldPage, error) {
	root := s.config.OutputDir
	if root == "" {
		root = s.config.DocsDir
	}

	var pages []ScaffoldPage

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)

		if info.IsDir() {
			if rel != "." && skipScaffoldDir(filepath.Base(path)) {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.EqualFold(filepath.Ext(path), ".md") {
			return nil
		}

		// The scaffold's own landing page is not a documentation page.
		if rel == "index.md" {
			return nil
		}

		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("scaffold: read %s: %w", path, readErr)
		}

		pages = append(pages, s.describePage(path, rel, string(content)))
		return nil
	})

	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	sort.Slice(pages, func(i, j int) bool {
		if pages[i].Language != pages[j].Language {
			return pages[i].Language < pages[j].Language
		}
		return pages[i].Link < pages[j].Link
	})

	return pages, nil
}

func (s *Scaffold) describePage(path, rel, content string) ScaffoldPage {
	frontMatter, body := splitFrontMatter(content)

	page := ScaffoldPage{
		Language: "",
		Title:    frontMatterValue(frontMatter, "title"),
		Symbols:  extractSymbols(body),
	}

	if parts := strings.SplitN(rel, "/", 2); len(parts) == 2 {
		page.Language = parts[0]
	}

	if page.Title == "" {
		page.Title = firstHeading(body)
	}
	if page.Title == "" {
		page.Title = strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	}

	// A permalink is what the site actually serves, so it is preferred over a
	// guessed file path. The normalizer writes one onto every generated page.
	if permalink := frontMatterValue(frontMatter, "permalink"); permalink != "" {
		page.Link = s.applyBaseURL(permalink)
	} else {
		page.Link = s.relativeLink(path)
	}

	return page
}

// applyBaseURL prefixes a root-absolute link with the configured base path. A
// site published under a base path serves "/x" as "<base>/x", so an unprefixed
// absolute permalink would answer 404. Relative links resolve against the page
// that carries them and are left alone.
func (s *Scaffold) applyBaseURL(link string) string {
	base := strings.TrimSuffix(s.config.BaseURL, "/")
	if base == "" || !strings.HasPrefix(link, "/") {
		return link
	}

	return base + link
}

// relativeLink builds a link from the site root to a page that carries no
// permalink. Jekyll publishes page.md as page.html.
func (s *Scaffold) relativeLink(path string) string {
	rel, err := filepath.Rel(s.config.DocsDir, path)
	if err != nil {
		rel = filepath.Base(path)
	}

	rel = filepath.ToSlash(rel)
	return strings.TrimSuffix(rel, filepath.Ext(rel)) + ".html"
}

func (s *Scaffold) writeConfig(path string) (bool, error) {
	if _, err := os.Stat(path); err == nil {
		// A consumer-owned config is never clobbered.
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("scaffold: stat %s: %w", path, err)
	}

	var b strings.Builder
	b.WriteString("# Minimal Jekyll configuration written by AurumCode.\n")
	b.WriteString("# It is created only when absent: edit it freely, it will not be overwritten.\n")
	b.WriteString("title: " + yamlScalar(s.config.Title) + "\n")
	b.WriteString("description: " + yamlScalar(s.config.Description) + "\n")
	if s.config.BaseURL != "" {
		b.WriteString("baseurl: " + yamlScalar(s.config.BaseURL) + "\n")
	}
	b.WriteString("theme: jekyll-theme-primer\n")
	b.WriteString("markdown: kramdown\n")
	b.WriteString("defaults:\n")
	b.WriteString("  - scope:\n")
	b.WriteString("      path: \"\"\n")
	b.WriteString("    values:\n")
	b.WriteString("      layout: default\n")
	b.WriteString("exclude:\n")
	b.WriteString("  - Gemfile\n")
	b.WriteString("  - Gemfile.lock\n")
	b.WriteString("  - vendor\n")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return false, fmt.Errorf("scaffold: write %s: %w", path, err)
	}

	return true, nil
}

// writeIndex writes the landing page. Front matter is owned by the scaffold so
// repeated runs converge on the same bytes; prose already in the file - a
// hand-written introduction or an LLM welcome page - is preserved above the
// generated listing.
func (s *Scaffold) writeIndex(path string, pages []ScaffoldPage) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("scaffold: read %s: %w", path, err)
	}

	intro := ""
	if err == nil {
		_, body := splitFrontMatter(string(existing))
		intro = stripGeneratedBlock(body)
	}

	intro = strings.TrimSpace(intro)
	if intro == "" {
		intro = "# " + s.config.Title + "\n\n" + s.config.Description
	}

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("layout: default\n")
	b.WriteString("title: Home\n")
	b.WriteString("nav_order: 1\n")
	b.WriteString("permalink: /\n")
	b.WriteString("---\n\n")
	b.WriteString(intro)
	b.WriteString("\n\n")
	b.WriteString(renderPageBlock(pages))

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("scaffold: write %s: %w", path, err)
	}

	return nil
}

// renderPageBlock renders the delimited listing of generated pages.
func renderPageBlock(pages []ScaffoldPage) string {
	var b strings.Builder
	b.WriteString(scaffoldBlockStart)
	b.WriteString("\n\n## Generated API documentation\n\n")

	if len(pages) == 0 {
		b.WriteString("No documentation pages were generated for this run.\n")
		b.WriteString("\n")
		b.WriteString(scaffoldBlockEnd)
		b.WriteString("\n")
		return b.String()
	}

	currentLanguage := "\x00"
	for _, page := range pages {
		if page.Language != currentLanguage {
			currentLanguage = page.Language
			b.WriteString("### " + languageDisplayName(page.Language) + "\n\n")
		}

		b.WriteString(fmt.Sprintf("- [%s](%s)\n", markdownLabel(page.Title), markdownDestination(page.Link)))

		symbols := page.Symbols
		truncated := 0
		if len(symbols) > scaffoldMaxSymbols {
			truncated = len(symbols) - scaffoldMaxSymbols
			symbols = symbols[:scaffoldMaxSymbols]
		}

		for _, symbol := range symbols {
			b.WriteString(fmt.Sprintf("  - `%s`\n", symbol))
		}
		if truncated > 0 {
			b.WriteString(fmt.Sprintf("  - and %d more\n", truncated))
		}

		b.WriteString("\n")
	}

	b.WriteString(scaffoldBlockEnd)
	b.WriteString("\n")

	return b.String()
}

// stripGeneratedBlock removes a previously generated listing so it can be
// replaced rather than duplicated.
func stripGeneratedBlock(body string) string {
	start := strings.Index(body, scaffoldBlockStart)
	if start < 0 {
		return body
	}

	end := strings.Index(body, scaffoldBlockEnd)
	if end < 0 || end < start {
		return body[:start]
	}

	return body[:start] + body[end+len(scaffoldBlockEnd):]
}

// splitFrontMatter separates YAML front matter from the markdown body.
func splitFrontMatter(content string) (frontMatter, body string) {
	normalized := strings.ReplaceAll(content, "\r\n", "\n")
	if !strings.HasPrefix(normalized, "---\n") {
		return "", normalized
	}

	rest := normalized[len("---\n"):]
	if idx := strings.Index(rest, "\n---\n"); idx >= 0 {
		return rest[:idx], rest[idx+len("\n---\n"):]
	}
	if strings.HasSuffix(rest, "\n---") {
		return strings.TrimSuffix(rest, "\n---"), ""
	}

	return "", normalized
}

// frontMatterValue reads a top-level scalar key. It deliberately does not pull
// in a YAML parser: the scaffold only needs title and permalink, both written by
// this repository's own normalizer.
func frontMatterValue(frontMatter, key string) string {
	for _, line := range strings.Split(frontMatter, "\n") {
		if strings.HasPrefix(line, " ") || strings.HasPrefix(line, "\t") {
			continue
		}

		name, value, found := strings.Cut(line, ":")
		if !found || strings.TrimSpace(name) != key {
			continue
		}

		return strings.Trim(strings.TrimSpace(value), `"'`)
	}

	return ""
}

// extractSymbols collects the documented symbols a page describes, in document
// order, from its second-level and deeper headings.
func extractSymbols(body string) []string {
	var symbols []string
	seen := map[string]struct{}{}
	inFence := false

	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}

		match := scaffoldHeading.FindStringSubmatch(trimmed)
		if match == nil || len(match[1]) < 2 {
			continue
		}

		symbol := cleanHeadingText(match[2])
		if symbol == "" {
			continue
		}
		if _, structural := structuralHeadings[strings.ToLower(symbol)]; structural {
			continue
		}
		if _, duplicate := seen[symbol]; duplicate {
			continue
		}

		seen[symbol] = struct{}{}
		symbols = append(symbols, symbol)
	}

	return symbols
}

// firstHeading returns the text of the page's first level-one heading.
func firstHeading(body string) string {
	inFence := false

	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}

		if match := scaffoldHeading.FindStringSubmatch(trimmed); match != nil && len(match[1]) == 1 {
			return cleanHeadingText(match[2])
		}
	}

	return ""
}

// cleanHeadingText reduces a heading to plain text: documentation generators
// wrap symbol names in anchors, links and escapes that must not leak into the
// index.
func cleanHeadingText(text string) string {
	text = scaffoldHTMLTag.ReplaceAllString(text, "")
	text = scaffoldMarkdownLink.ReplaceAllString(text, "$1")
	text = scaffoldEscape.ReplaceAllString(text, "$1")
	text = strings.ReplaceAll(text, "`", "")
	text = strings.TrimSpace(text)
	text = strings.TrimSuffix(text, "#")

	return strings.TrimSpace(text)
}

// markdownLabel makes text safe to sit inside a link label: brackets would end
// the label early and any line break would end the list item entirely.
func markdownLabel(text string) string {
	folded := strings.Join(strings.Fields(text), " ")
	return strings.NewReplacer(`\`, `\\`, `[`, `\[`, `]`, `\]`).Replace(folded)
}

// markdownDestination percent-encodes the bytes that would terminate a "(...)"
// link destination. A file name may legally contain spaces, parentheses and
// even newlines, and any of them silently turns the entry into plain text.
// "%" is left intact so an already-encoded permalink is not encoded twice.
func markdownDestination(link string) string {
	var b strings.Builder

	for i := 0; i < len(link); i++ {
		c := link[i]
		switch {
		case c <= 0x20, c >= 0x7f, c == '(', c == ')', c == '<', c == '>',
			c == '"', c == '\'', c == '`', c == '\\', c == '[', c == ']':
			fmt.Fprintf(&b, "%%%02X", c)
		default:
			b.WriteByte(c)
		}
	}

	return b.String()
}

// languageDisplayName renders a language directory name the way its community
// writes it.
func languageDisplayName(language string) string {
	language = strings.Join(strings.Fields(language), " ")

	switch strings.ToLower(language) {
	case "":
		return "General"
	case "go":
		return "Go"
	case "javascript":
		return "JavaScript"
	case "typescript":
		return "TypeScript"
	case "python":
		return "Python"
	case "csharp":
		return "C#"
	case "cpp":
		return "C++"
	case "rust":
		return "Rust"
	case "bash":
		return "Bash"
	case "powershell":
		return "PowerShell"
	case "java":
		return "Java"
	default:
		// Slicing the first byte would split a multi-byte rune and emit
		// mojibake for any non-ASCII directory name.
		first, size := utf8.DecodeRuneInString(language)
		if first == utf8.RuneError {
			return language
		}
		return string(unicode.ToUpper(first)) + language[size:]
	}
}

// skipScaffoldDir skips build output and tooling directories that hold copies of
// the generated pages.
func skipScaffoldDir(name string) bool {
	switch name {
	case "_site", ".jekyll-cache", ".sass-cache", "node_modules", ".git", "vendor":
		return true
	}

	return false
}

// yamlScalar renders a value as a YAML double-quoted scalar. The title comes
// from a repository directory name, which may legally hold quotes, backslashes,
// line breaks and control characters; an unescaped line break in particular ends
// the scalar at a column the parser rejects or silently folds away.
func yamlScalar(value string) string {
	var b strings.Builder
	b.WriteByte('"')

	for _, r := range value {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			switch {
			case r < 0x20, r >= 0x7f && r <= 0x9f:
				fmt.Fprintf(&b, `\x%02x`, r)
			case r == 0x2028, r == 0x2029, r == 0xfeff:
				fmt.Fprintf(&b, `\u%04x`, r)
			default:
				b.WriteRune(r)
			}
		}
	}

	b.WriteByte('"')
	return b.String()
}
