package site

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

// The generated page listing is delimited so a second run replaces it instead of
// appending a duplicate, and so hand-written or LLM-written prose above it
// survives untouched.
const (
	scaffoldBlockStart = "<!-- aurumcode:pages:start -->"
	scaffoldBlockEnd   = "<!-- aurumcode:pages:end -->"
)

// scaffoldMaxSymbols bounds how many symbols a single page contributes to the
// index. A package with hundreds of exported symbols would otherwise turn the
// landing page into a wall of text.
const scaffoldMaxSymbols = 20

// structuralHeadings are headings documentation tools emit for navigation rather
// than for a documented symbol. Listing them again on the index is noise.
var structuralHeadings = map[string]struct{}{
	"index":    {},
	"contents": {},
	"overview": {},
}

var (
	scaffoldHTMLTag      = regexp.MustCompile(`<[^>]*>`)
	scaffoldMarkdownLink = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)
	scaffoldEscape       = regexp.MustCompile("\\\\([\\\\`*_{}\\[\\]()#+\\-.!])")
	scaffoldHeading      = regexp.MustCompile(`^(#{1,6})\s+(.*)$`)
)

// ScaffoldConfig configures the deterministic site scaffold.
type ScaffoldConfig struct {
	// DocsDir is the site root: index.md and _config.yml are written there.
	DocsDir string

	// OutputDir holds the generated per-language markdown that the index lists.
	OutputDir string

	// Title and Description name the site in _config.yml and on the index page.
	Title       string
	Description string

	// BaseURL is the Jekyll baseurl, e.g. "/my-repo" for a project Pages site.
	BaseURL string

	// GeneratedPages lists the markdown files this run actually produced. When
	// it is set it is authoritative and the output directory is not walked.
	//
	// Walking is a guess: it cannot tell a page this run generated from a file
	// that merely shares the directory, and the default OutputDir (.aurumcode)
	// also holds the product's own prompt templates and rule files. Passing the
	// list removes the guess entirely. Paths may be absolute or relative to
	// OutputDir.
	GeneratedPages []string
}

// ScaffoldPage is one generated documentation page as the index sees it.
type ScaffoldPage struct {
	Language string
	Title    string
	Link     string
	Symbols  []string

	// Source is the page's path relative to DocsDir, in slash form. It is what
	// the site config's exclude list is matched against, since Jekyll excludes
	// source paths rather than the permalinks they publish under.
	Source string
}

// ScaffoldResult reports what the scaffold left on disk.
type ScaffoldResult struct {
	IndexPath     string
	ConfigPath    string
	Pages         []ScaffoldPage
	ConfigCreated bool

	// ExcludePatterns holds the exclude entries read from a pre-existing
	// _config.yml. It is empty when the scaffold wrote the config itself.
	ExcludePatterns []string

	// ExcludedPages names the pages that were listed on the index but that the
	// consumer's own exclude list keeps out of the build. Each one is published
	// as a 404. The scaffold never rewrites a consumer's config, so reporting
	// is the only honest thing it can do about the contradiction.
	ExcludedPages []string
}

// Scaffold turns a directory of generated markdown into something a static site
// host can actually serve.
//
// It exists because markdown alone is not a site: without an index.md the
// published root is a 404, and without a _config.yml the host has no reason to
// render the .md files as pages. Both files are produced deterministically from
// what is on disk, with no LLM involved, so a consumer without any provider key
// still gets a browsable site. The LLM welcome page remains an enrichment: when
// it ran, its prose is kept above the generated page listing.
type Scaffold struct {
	config ScaffoldConfig
}

// NewScaffold creates a scaffold generator.
func NewScaffold(config ScaffoldConfig) *Scaffold {
	if config.Title == "" {
		config.Title = "Documentation"
	}
	if config.Description == "" {
		config.Description = "API documentation generated by AurumCode."
	}

	return &Scaffold{config: config}
}

// Generate writes _config.yml and index.md. It is safe to run repeatedly: the
// generated page listing is replaced in place and an existing _config.yml is
// never overwritten, so a consumer can customise the site config.
func (s *Scaffold) Generate() (*ScaffoldResult, error) {
	if s.config.DocsDir == "" {
		return nil, fmt.Errorf("scaffold: DocsDir is required")
	}

	pages, err := s.collectPages()
	if err != nil {
		return nil, err
	}

	if err := os.MkdirAll(s.config.DocsDir, 0o755); err != nil {
		return nil, fmt.Errorf("scaffold: create %s: %w", s.config.DocsDir, err)
	}

	result := &ScaffoldResult{
		IndexPath:  filepath.Join(s.config.DocsDir, "index.md"),
		ConfigPath: filepath.Join(s.config.DocsDir, "_config.yml"),
		Pages:      pages,
	}

	created, excludes, err := s.writeConfig(result.ConfigPath)
	if err != nil {
		return nil, err
	}
	result.ConfigCreated = created

	// A config the scaffold wrote itself never contradicts the index: it has no
	// exclude entries for the directories the index just listed. Reporting is
	// only meaningful - and only honest - against a consumer's own file.
	if !created {
		result.ExcludePatterns = excludes
		result.ExcludedPages = excludedPages(excludes, pages)
	}

	if err := s.writeIndex(result.IndexPath, pages); err != nil {
		return nil, err
	}

	return result, nil
}

// collectPages records how the index should link to the pages this run
// produced. When the caller passed GeneratedPages, that list is authoritative
// and is the only thing read: it names exactly the files this run wrote, so
// nothing else under OutputDir is even opened.
//
// Without that list, collectPages falls back to walking OutputDir and treating
// every ".md" file it finds as a generated page. That fallback is a guess: it
// cannot distinguish a page this run wrote from a file that merely shares the
// directory, and the default OutputDir (.aurumcode) also holds the product's
// own prompt templates and rule files, which are input, not output.
// skipScaffoldDir excludes the directories known to hold such input so the
// walk does not index them, but a caller that wants a precise answer should
// pass GeneratedPages instead of relying on that fallback.
func (s *Scaffold) collectPages() ([]ScaffoldPage, error) {
	root := s.config.OutputDir
	if root == "" {
		root = s.config.DocsDir
	}

	var pages []ScaffoldPage
	var err error

	if len(s.config.GeneratedPages) > 0 {
		pages, err = s.collectListedPages(root)
	} else {
		pages, err = s.collectWalkedPages(root)
	}
	if err != nil {
		return nil, err
	}

	sort.Slice(pages, func(i, j int) bool {
		if pages[i].Language != pages[j].Language {
			return pages[i].Language < pages[j].Language
		}
		return pages[i].Link < pages[j].Link
	})

	return pages, nil
}

// collectListedPages reads exactly the files GeneratedPages names. A path may
// be absolute or relative to root; either way it is read directly, with no
// directory walk and no guessing about what else lives alongside it.
func (s *Scaffold) collectListedPages(root string) ([]ScaffoldPage, error) {
	var pages []ScaffoldPage

	for _, listed := range s.config.GeneratedPages {
		path := listed
		if !filepath.IsAbs(path) {
			path = filepath.Join(root, path)
		}

		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil, fmt.Errorf("scaffold: read %s: %w", path, readErr)
		}

		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			rel = filepath.Base(path)
		}
		rel = filepath.ToSlash(rel)

		if rel == "index.md" {
			continue
		}

		pages = append(pages, s.describePage(path, rel, string(content)))
	}

	return pages, nil
}

// collectWalkedPages reads every generated markdown page under root by
// walking the directory tree. It is the fallback used when the caller did not
// state which files this run wrote; see collectPages for why that is a guess.
func (s *Scaffold) collectWalkedPages(root string) ([]ScaffoldPage, error) {
	var pages []ScaffoldPage

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)

		if info.IsDir() {
			if rel != "." && skipScaffoldDir(filepath.Base(path)) {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.EqualFold(filepath.Ext(path), ".md") {
			return nil
		}

		// The scaffold's own landing page is not a documentation page.
		if rel == "index.md" {
			return nil
		}

		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("scaffold: read %s: %w", path, readErr)
		}

		pages = append(pages, s.describePage(path, rel, string(content)))
		return nil
	})

	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	return pages, nil
}

func (s *Scaffold) describePage(path, rel, content string) ScaffoldPage {
	frontMatter, body := splitFrontMatter(content)

	page := ScaffoldPage{
		Language: "",
		Title:    frontMatterValue(frontMatter, "title"),
		Symbols:  extractSymbols(body),
		Source:   s.sourceRel(path),
	}

	if parts := strings.SplitN(rel, "/", 2); len(parts) == 2 {
		page.Language = parts[0]
	}

	if page.Title == "" {
		page.Title = firstHeading(body)
	}
	if page.Title == "" {
		page.Title = strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	}

	// A permalink is what the site actually serves, so it is preferred over a
	// guessed file path. The normalizer writes one onto every generated page.
	if permalink := frontMatterValue(frontMatter, "permalink"); permalink != "" {
		page.Link = s.applyBaseURL(permalink)
	} else {
		page.Link = s.relativeLink(path)
	}

	return page
}

// applyBaseURL prefixes a root-absolute link with the configured base path. A
// site published under a base path serves "/x" as "<base>/x", so an unprefixed
// absolute permalink would answer 404. Relative links resolve against the page
// that carries them and are left alone.
func (s *Scaffold) applyBaseURL(link string) string {
	base := strings.TrimSuffix(s.config.BaseURL, "/")
	if base == "" || !strings.HasPrefix(link, "/") {
		return link
	}

	return base + link
}

// relativeLink builds a link from the site root to a page that carries no
// permalink. Jekyll publishes page.md as page.html.
func (s *Scaffold) relativeLink(path string) string {
	rel, err := filepath.Rel(s.config.DocsDir, path)
	if err != nil {
		rel = filepath.Base(path)
	}

	rel = filepath.ToSlash(rel)
	return strings.TrimSuffix(rel, filepath.Ext(rel)) + ".html"
}

// sourceRel resolves a page's path relative to DocsDir, in slash form. Jekyll
// matches its exclude list against source paths - the ones on disk under the
// site root - not against the permalinks those files publish under, so this is
// the value ExcludedPages must compare exclude patterns against.
func (s *Scaffold) sourceRel(path string) string {
	rel, err := filepath.Rel(s.config.DocsDir, path)
	if err != nil {
		rel = filepath.Base(path)
	}

	return filepath.ToSlash(rel)
}

// writeConfig writes _config.yml when it is absent. When it already exists it
// is left untouched - a consumer-owned config is never clobbered - but its
// exclude list is read and returned so the caller can report any contradiction
// between what it hides and what the index just listed.
func (s *Scaffold) writeConfig(path string) (bool, []string, error) {
	if existing, err := os.ReadFile(path); err == nil {
		return false, parseExcludeList(string(existing)), nil
	} else if !os.IsNotExist(err) {
		return false, nil, fmt.Errorf("scaffold: stat %s: %w", path, err)
	}

	var b strings.Builder
	b.WriteString("# Minimal Jekyll configuration written by AurumCode.\n")
	b.WriteString("# It is created only when absent: edit it freely, it will not be overwritten.\n")
	b.WriteString("title: " + yamlScalar(s.config.Title) + "\n")
	b.WriteString("description: " + yamlScalar(s.config.Description) + "\n")
	if s.config.BaseURL != "" {
		b.WriteString("baseurl: " + yamlScalar(s.config.BaseURL) + "\n")
	}
	b.WriteString("theme: jekyll-theme-primer\n")
	b.WriteString("markdown: kramdown\n")
	b.WriteString("defaults:\n")
	b.WriteString("  - scope:\n")
	b.WriteString("      path: \"\"\n")
	b.WriteString("    values:\n")
	b.WriteString("      layout: default\n")
	b.WriteString("exclude:\n")
	b.WriteString("  - Gemfile\n")
	b.WriteString("  - Gemfile.lock\n")
	b.WriteString("  - vendor\n")
	b.WriteString("  - skills\n")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return false, nil, fmt.Errorf("scaffold: write %s: %w", path, err)
	}

	return true, nil, nil
}

// writeIndex writes the landing page. Front matter is owned by the scaffold so
// repeated runs converge on the same bytes; prose already in the file - a
// hand-written introduction or an LLM welcome page - is preserved above the
// generated listing.
func (s *Scaffold) writeIndex(path string, pages []ScaffoldPage) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("scaffold: read %s: %w", path, err)
	}

	intro := ""
	if err == nil {
		_, body := splitFrontMatter(string(existing))
		intro = stripGeneratedBlock(body)
	}

	intro = strings.TrimSpace(intro)
	if intro == "" {
		intro = "# " + s.config.Title + "\n\n" + s.config.Description
	}

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("layout: default\n")
	b.WriteString("title: Home\n")
	b.WriteString("nav_order: 1\n")
	b.WriteString("permalink: /\n")
	b.WriteString("---\n\n")
	b.WriteString(intro)
	b.WriteString("\n\n")
	b.WriteString(renderPageBlock(pages))

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("scaffold: write %s: %w", path, err)
	}

	return nil
}

// renderPageBlock renders the delimited listing of generated pages.
func renderPageBlock(pages []ScaffoldPage) string {
	var b strings.Builder
	b.WriteString(scaffoldBlockStart)
	b.WriteString("\n\n## Generated API documentation\n\n")

	if len(pages) == 0 {
		b.WriteString("No documentation pages were generated for this run.\n")
		b.WriteString("\n")
		b.WriteString(scaffoldBlockEnd)
		b.WriteString("\n")
		return b.String()
	}

	b.WriteString(fmt.Sprintf("> %d page(s) generated from the source tree. Use the navigation or choose a language below.\n\n", len(pages)))

	currentLanguage := "\x00"
	for _, page := range pages {
		if page.Language != currentLanguage {
			currentLanguage = page.Language
			b.WriteString("### " + languageDisplayName(page.Language) + "\n\n")
		}

		b.WriteString(fmt.Sprintf("- [%s](%s)\n", markdownLabel(page.Title), markdownDestination(page.Link)))

		symbols := page.Symbols
		truncated := 0
		if len(symbols) > scaffoldMaxSymbols {
			truncated = len(symbols) - scaffoldMaxSymbols
			symbols = symbols[:scaffoldMaxSymbols]
		}

		for _, symbol := range symbols {
			b.WriteString(fmt.Sprintf("  - `%s`\n", symbol))
		}
		if truncated > 0 {
			b.WriteString(fmt.Sprintf("  - and %d more\n", truncated))
		}

		b.WriteString("\n")
	}

	b.WriteString(scaffoldBlockEnd)
	b.WriteString("\n")

	return b.String()
}

// stripGeneratedBlock removes a previously generated listing so it can be
// replaced rather than duplicated.
func stripGeneratedBlock(body string) string {
	start := strings.Index(body, scaffoldBlockStart)
	if start < 0 {
		return body
	}

	end := strings.Index(body, scaffoldBlockEnd)
	if end < 0 || end < start {
		return body[:start]
	}

	return body[:start] + body[end+len(scaffoldBlockEnd):]
}

// splitFrontMatter separates YAML front matter from the markdown body.
func splitFrontMatter(content string) (frontMatter, body string) {
	normalized := strings.ReplaceAll(content, "\r\n", "\n")
	if !strings.HasPrefix(normalized, "---\n") {
		return "", normalized
	}

	rest := normalized[len("---\n"):]
	if idx := strings.Index(rest, "\n---\n"); idx >= 0 {
		return rest[:idx], rest[idx+len("\n---\n"):]
	}
	if strings.HasSuffix(rest, "\n---") {
		return strings.TrimSuffix(rest, "\n---"), ""
	}

	return "", normalized
}

// frontMatterValue reads a top-level scalar key. It deliberately does not pull
// in a YAML parser: the scaffold only needs title and permalink, both written by
// this repository's own normalizer.
func frontMatterValue(frontMatter, key string) string {
	for _, line := range strings.Split(frontMatter, "\n") {
		if strings.HasPrefix(line, " ") || strings.HasPrefix(line, "\t") {
			continue
		}

		name, value, found := strings.Cut(line, ":")
		if !found || strings.TrimSpace(name) != key {
			continue
		}

		return strings.Trim(strings.TrimSpace(value), `"'`)
	}

	return ""
}

// extractSymbols collects the documented symbols a page describes, in document
// order, from its second-level and deeper headings.
func extractSymbols(body string) []string {
	var symbols []string
	seen := map[string]struct{}{}
	inFence := false

	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}

		match := scaffoldHeading.FindStringSubmatch(trimmed)
		if match == nil || len(match[1]) < 2 {
			continue
		}

		symbol := cleanHeadingText(match[2])
		if symbol == "" {
			continue
		}
		if _, structural := structuralHeadings[strings.ToLower(symbol)]; structural {
			continue
		}
		if _, duplicate := seen[symbol]; duplicate {
			continue
		}

		seen[symbol] = struct{}{}
		symbols = append(symbols, symbol)
	}

	return symbols
}

// firstHeading returns the text of the page's first level-one heading.
func firstHeading(body string) string {
	inFence := false

	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}

		if match := scaffoldHeading.FindStringSubmatch(trimmed); match != nil && len(match[1]) == 1 {
			return cleanHeadingText(match[2])
		}
	}

	return ""
}

// cleanHeadingText reduces a heading to plain text: documentation generators
// wrap symbol names in anchors, links and escapes that must not leak into the
// index.
func cleanHeadingText(text string) string {
	text = scaffoldHTMLTag.ReplaceAllString(text, "")
	text = scaffoldMarkdownLink.ReplaceAllString(text, "$1")
	text = scaffoldEscape.ReplaceAllString(text, "$1")
	text = strings.ReplaceAll(text, "`", "")
	text = strings.TrimSpace(text)
	text = strings.TrimSuffix(text, "#")

	return strings.TrimSpace(text)
}

// markdownLabel makes text safe to sit inside a link label: brackets would end
// the label early and any line break would end the list item entirely.
func markdownLabel(text string) string {
	folded := strings.Join(strings.Fields(text), " ")
	return strings.NewReplacer(`\`, `\\`, `[`, `\[`, `]`, `\]`).Replace(folded)
}

// markdownDestination percent-encodes the bytes that would terminate a "(...)"
// link destination. A file name may legally contain spaces, parentheses and
// even newlines, and any of them silently turns the entry into plain text.
// "%" is left intact so an already-encoded permalink is not encoded twice.
func markdownDestination(link string) string {
	var b strings.Builder

	for i := 0; i < len(link); i++ {
		c := link[i]
		switch {
		case c <= 0x20, c >= 0x7f, c == '(', c == ')', c == '<', c == '>',
			c == '"', c == '\'', c == '`', c == '\\', c == '[', c == ']':
			fmt.Fprintf(&b, "%%%02X", c)
		default:
			b.WriteByte(c)
		}
	}

	return b.String()
}

// languageDisplayName renders a language directory name the way its community
// writes it.
func languageDisplayName(language string) string {
	language = strings.Join(strings.Fields(language), " ")

	switch strings.ToLower(language) {
	case "":
		return "General"
	case "go":
		return "Go"
	case "javascript":
		return "JavaScript"
	case "typescript":
		return "TypeScript"
	case "python":
		return "Python"
	case "csharp":
		return "C#"
	case "cpp":
		return "C++"
	case "rust":
		return "Rust"
	case "bash":
		return "Bash"
	case "powershell":
		return "PowerShell"
	case "java":
		return "Java"
	default:
		// Slicing the first byte would split a multi-byte rune and emit
		// mojibake for any non-ASCII directory name.
		first, size := utf8.DecodeRuneInString(language)
		if first == utf8.RuneError {
			return language
		}
		return string(unicode.ToUpper(first)) + language[size:]
	}
}

// parseExcludeList reads the top-level "exclude:" sequence from a Jekyll site
// config. It is a purpose-built reader, not a YAML parser: it only needs to
// find the block-sequence items under a top-level "exclude:" key, strip their
// inline "# ..." comments and surrounding quotes, and stop at the next
// top-level key. That is the exact shape both this repository's own
// .aurumcode/_config.yml and Jekyll's own documentation use.
func parseExcludeList(config string) []string {
	var excludes []string
	inExclude := false

	for _, line := range strings.Split(strings.ReplaceAll(config, "\r\n", "\n"), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}

		topLevel := line[0] != ' ' && line[0] != '\t'

		if !inExclude {
			if topLevel && strings.HasPrefix(strings.TrimSpace(line), "exclude:") {
				inExclude = true
			}
			continue
		}

		if topLevel {
			// A new top-level key ends the exclude block.
			inExclude = false
			continue
		}

		item := strings.TrimSpace(line)
		if !strings.HasPrefix(item, "-") {
			continue
		}
		item = strings.TrimSpace(strings.TrimPrefix(item, "-"))

		if idx := strings.Index(item, "#"); idx >= 0 {
			item = strings.TrimSpace(item[:idx])
		}
		item = strings.Trim(item, `"'`)

		if item != "" {
			excludes = append(excludes, item)
		}
	}

	return excludes
}

// excludeHidesPage reports whether any exclude entry keeps a page's source
// path out of the build, and which entry does it. Jekyll's exclude matches a
// path either exactly or as a directory prefix, so "bash/" (or "bash") hides
// "bash/deploy.sh.md" but not "bash-utils/deploy.sh.md".
func excludeHidesPage(excludes []string, source string) (bool, string) {
	source = filepath.ToSlash(source)

	for _, pattern := range excludes {
		dir := strings.TrimSuffix(strings.TrimSpace(pattern), "/")
		if dir == "" {
			continue
		}
		if source == dir || strings.HasPrefix(source, dir+"/") {
			return true, pattern
		}
	}

	return false, ""
}

// excludedPages names, in listing order, the pages whose Source a consumer's
// own exclude list keeps out of the build. The scaffold never rewrites that
// config, so surfacing the contradiction is the only honest response to it.
func excludedPages(excludes []string, pages []ScaffoldPage) []string {
	var hidden []string

	for _, page := range pages {
		if ok, _ := excludeHidesPage(excludes, page.Source); ok {
			hidden = append(hidden, page.Source)
		}
	}

	return hidden
}

// skipScaffoldDir skips build output, tooling directories, and the product's
// own input directories that happen to live under the default OutputDir.
//
// This is the minimum fix for the ghost-index defect, not the ideal one: it is
// a fixed list of names, so it only protects against the input directories
// known today (.aurumcode/prompts, read by internal/documentation/welcome, and
// .aurumcode/rules) and says nothing about a directory added later. The ideal
// fix is the caller passing ScaffoldConfig.GeneratedPages, which removes the
// walk - and the guessing - entirely. Wiring that from the pipeline that calls
// NewScaffold is outside this package; until it happens, this fallback is what
// actually runs in production.
func skipScaffoldDir(name string) bool {
	switch name {
	case "_site", ".jekyll-cache", ".sass-cache", "node_modules", ".git", "vendor",
		"prompts", "rules", "skills", "reviews":
		return true
	}

	return false
}

// yamlScalar renders a value as a YAML double-quoted scalar. The title comes
// from a repository directory name, which may legally hold quotes, backslashes,
// line breaks and control characters; an unescaped line break in particular ends
// the scalar at a column the parser rejects or silently folds away.
func yamlScalar(value string) string {
	var b strings.Builder
	b.WriteByte('"')

	for _, r := range value {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			switch {
			case r < 0x20, r >= 0x7f && r <= 0x9f:
				fmt.Fprintf(&b, `\x%02x`, r)
			case r == 0x2028, r == 0x2029, r == 0xfeff:
				fmt.Fprintf(&b, `\u%04x`, r)
			default:
				b.WriteRune(r)
			}
		}
	}

	b.WriteByte('"')
	return b.String()
}
